/* Original sprite arena. All HP, damage and cooldowns are demonstration state only. */
const battleAssets={atlas:'assets/champion-combat-atlas-v1.png',arena:'assets/champion-arena-v1.png'};
const battlePrototypeNames=['光法師','重甲劍士','狐術師'];
const battleSkillFX=[['光束禁錮','稜光護盾','魔光爆裂','終極光束'],['突進斬擊','鋼鐵護盾','旋轉劍舞','天降巨劍'],['往返靈珠','三重狐火','魅惑光彈','三段靈躍']];
let leagueOpponent='Garen',battleDemo=true,battleRenderer=null;
function battleKind(c){if(c.id==='Ahri')return 2;if(c.id==='Lux')return 0;if(c.id==='Garen')return 1;const t=c.tags||[];return t.includes('Fighter')||t.includes('Tank')?1:t.includes('Mage')||t.includes('Support')?0:2;}
function battleActor(kind,x){return {kind,x,target:x,hp:1000,maxHP:1000,shield:0,shieldUntil:0,pose:0,poseUntil:0,busyUntil:0,rootUntil:0,cooldowns:[0,0,0,0],facing:1};}
class BattleSimulation{
 constructor(){this.reset(0,1);}
 reset(playerKind=0,enemyKind=1){this.time=0;this.actors=[battleActor(playerKind,245),battleActor(enemyKind,715)];this.actors[1].facing=-1;this.events=[];this.projectiles=[];this.effects=[];this.numbers=[];this.winner=null;this.shake=0;this.auto=false;this.nextAuto=1.2;this.enemyEnabled=true;this.nextEnemy=2.5;this.sequence=0;this.allowedSkills=[-1,0,1,2,3];this.log='點選地面走位，或使用普攻與 Q / W / E / R。';}
 later(delay,fn){this.events.push({at:this.time+delay,fn});}
 effect(type,x,color,duration=0.65,extra={}){this.effects.push({type,x,color,start:this.time,end:this.time+duration,...extra});}
 pose(actor,frame,duration){actor.pose=frame;actor.poseUntil=this.time+duration;}
 damage(target,amount,color='#fff',root=0){if(target.hp<=0||this.winner!==null)return;const absorbed=Math.min(target.shield,amount);target.shield-=absorbed;const value=Math.max(0,amount-absorbed);target.hp=Math.max(0,target.hp-value);target.rootUntil=Math.max(target.rootUntil,this.time+root);this.pose(target,target.hp?4:5,target.hp?0.26:99999);this.numbers.push({x:target.x,value:absorbed&&!value?'格擋':String(value),color,start:this.time,end:this.time+0.9});this.effect('impact',target.x,color,.55);this.shake=Math.max(this.shake,value>=200?8:3);if(!target.hp){this.winner=this.actors.indexOf(target)===0?1:0;this.auto=false;this.log='演示結束 · '+(this.winner===0?'玩家勝利':'對手勝利')+'，不產生學習或競賽積分。';}}
 projectile(source,target,type,color,damage,speed=640,root=0,returning=false){if(source.hp<=0)return;this.projectiles.push({x:source.x+source.facing*45,from:source.x,to:target.x,source,target,type,color,damage,speed,root,returning,phase:0});}
 cast(index,side=0){if(!Number.isInteger(index)||index< -1||index>3||this.winner!==null)return false;const a=this.actors[side],b=this.actors[1-side],t=this.time;if(!a.hp||t<a.busyUntil||t<a.rootUntil||index>=0&&t<a.cooldowns[index])return false;
 a.busyUntil=t+(index===3?1.0:.6);if(index>=0)a.cooldowns[index]=t+[1.4,3,2.8,5][index];this.pose(a,2,.23);const colors=['#9fe4ff','#ffdc7f','#bdcaff'],color=colors[a.kind];this.effect('charge',a.x,color,.38);this.log=(side===0?'玩家':'對手')+' · '+(index===-1?'普攻':battleSkillFX[a.kind][index]);
 this.later(.23,()=>{if(!a.hp||this.winner!==null)return;this.pose(a,3,.4);
 if(index===-1){if(a.kind===1){a.target=Math.max(150,Math.min(810,b.x-a.facing*145));a.moveSpeed=600;const delay=Math.max(.2,Math.abs(a.target-a.x)/600);a.busyUntil=this.time+delay+.35;this.later(delay,()=>{if(a.hp&&Math.abs(a.x-b.x)<195){this.pose(a,3,.3);this.effect('slash',b.x,color,.42);this.damage(b,65,color);}});}else this.projectile(a,b,'orb',color,65,750);return;}
 if(index===1){a.shield=220;a.shieldUntil=this.time+2.7;this.effect('shield',a.x,color,2.7,{actor:a});if(a.kind===2){for(let i=0;i<3;i++)this.later(i*.17,()=>this.projectile(a,b,'flame','#77cfff',45,700));}return;}
 if(a.kind===0){if(index===0)this.projectile(a,b,'bolt',color,110,780,.7);if(index===2){const x=b.x;this.effect('zone',x,color,.9);this.later(.7,()=>{this.effect('blast',x,color,.65);if(Math.abs(b.x-x)<145)this.damage(b,155,color);});}if(index===3){this.effect('beam',a.x,'#e3fbff',.65,{to:b.x});this.damage(b,320,color);this.shake=10;}}
 if(a.kind===1){if(index===0){a.target=b.x-a.facing*135;a.moveSpeed=1400;this.effect('dash',a.x,color,.4,{to:a.target});this.later(.2,()=>{this.effect('slash',b.x,color,.5);this.damage(b,140,color);});}if(index===2){a.target=b.x-a.facing*110;a.moveSpeed=1100;this.effect('spin',a.x,color,1.2,{actor:a});for(let i=0;i<3;i++)this.later(.4+i*.25,()=>{if(a.hp&&Math.abs(a.x-b.x)<210)this.damage(b,75,color);});}if(index===3){this.effect('sword',b.x,color,.85);this.later(.35,()=>{this.damage(b,340,color);this.shake=12;});}}
 if(a.kind===2){if(index===0)this.projectile(a,b,'orb','#8dccff',100,620,0,true);if(index===2)this.projectile(a,b,'heart','#ff8dc4',130,600,.9);if(index===3){for(let i=0;i<3;i++)this.later(i*.27,()=>{if(!a.hp||this.winner!==null)return;const old=a.x;a.x=Math.max(155,Math.min(805,b.x-a.facing*(150+i%2*50)));a.target=a.x;this.effect('dash',old,'#b7d6ff',.42,{to:a.x});this.projectile(a,b,'flame','#a7dfff',85,850);});}}
 });return true;
 }
 move(x){const a=this.actors[0];if(this.winner!==null||this.time<a.rootUntil)return;a.target=Math.max(140,Math.min(820,x));}
 step(dt){dt=Math.min(Math.max(dt,0),.05);this.time+=dt;const due=this.events.filter(e=>e.at<=this.time);this.events=this.events.filter(e=>e.at>this.time);due.forEach(e=>e.fn());
 for(const a of this.actors){if(a.shieldUntil<this.time)a.shield=0;if(a.hp&&this.time>=a.rootUntil){const other=this.actors[a===this.actors[0]?1:0];a.facing=other.x>=a.x?1:-1;const d=a.target-a.x;a.x+=Math.sign(d)*Math.min(Math.abs(d),dt*(a.moveSpeed||250));if(this.time>=a.busyUntil)a.moveSpeed=250;if(Math.abs(d)>3&&this.time>=a.poseUntil)a.pose=1;else if(this.time>=a.poseUntil)a.pose=0;}}
 this.projectiles=this.projectiles.filter(p=>{if(this.winner!==null)return false;const goal=p.phase?p.source.x:p.target.x,dir=Math.sign(goal-p.x),dist=Math.abs(goal-p.x);p.x+=dir*Math.min(dist,p.speed*dt);if(dist>p.speed*dt+2)return true;if(!p.phase){this.damage(p.target,p.damage,p.color,p.root);if(p.returning&&p.source.hp){p.phase=1;return true;}}else this.damage(p.target,80,p.color);return false;});
 this.effects=this.effects.filter(e=>e.end>this.time);this.numbers=this.numbers.filter(e=>e.end>this.time);this.shake=Math.max(0,this.shake-dt*30);
 if(this.auto&&this.winner===null&&this.time>=this.nextAuto){const pattern=[-1,0,2,1,3].filter(i=>this.allowedSkills.includes(i));this.cast(pattern[this.sequence++%pattern.length]);this.nextAuto=this.time+1.1;}
 if(this.enemyEnabled&&this.winner===null&&this.time>=this.nextEnemy){this.cast(this.time%9>6?0:-1,1);this.nextEnemy=this.time+2.2;}
 }
}
class BattleCanvas{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.sim=new BattleSimulation();this.atlas=new Image();this.background=new Image();this.loaded=false;this.failed=false;this.visible=true;this.last=0;this.frame=0;this.key='';this.atlas.onload=()=>{this.loaded=true;this.status('角色素材載入完成。點選地面走位，或施放技能。');};this.atlas.onerror=()=>{this.failed=true;this.status('角色素材載入失敗，請重新整理。');};this.atlas.src=battleAssets.atlas;this.background.src=battleAssets.arena;
 this.resize();this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.intersection=new IntersectionObserver(entries=>{this.visible=entries[0]?.isIntersecting!==false;});this.intersection.observe(canvas);
 canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();if(r.width)this.sim.move((e.clientX-r.left)*960/r.width);});
 this.loop=this.loop.bind(this);this.frame=requestAnimationFrame(this.loop);
 }
 resize(){const ratio=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(960*ratio);this.canvas.height=Math.round(500*ratio);this.ratio=ratio;}
 status(s){const el=document.querySelector('#duel-status');if(el.textContent!==s)el.textContent=s;}
 loop(now){const dt=this.last?Math.min((now-this.last)/1000,.05):0;this.last=now;if(!document.hidden&&this.visible){this.sim.step(dt);this.draw();this.updateUI();}this.frame=requestAnimationFrame(this.loop);}
 updateUI(){const now=this.sim.time;document.querySelectorAll('[data-battle-skill]').forEach(b=>{const i=Number(b.dataset.battleSkill),left=this.sim.actors[0].cooldowns[i]-now,locked=!battleDemo&&leagueLevel()<leagueSkillLevels[i];b.disabled=locked||left>0||this.sim.winner!==null||!this.loaded;const text=b.querySelector('small');if(text)text.textContent=locked?'LV. '+leagueSkillLevels[i]+' 解鎖':left>0?left.toFixed(1)+'s':'施放';});document.querySelector('#battle-basic').disabled=!this.loaded||this.sim.winner!==null;const auto=document.querySelector('#duel-auto');auto.textContent=this.sim.auto?'停止自動對戰':'自動對戰';auto.setAttribute('aria-pressed',String(this.sim.auto));if(this.loaded)this.status(this.sim.log);}
 draw(){const c=this.ctx,s=this.sim,t=s.time;if(!c)return;c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,960,500);c.save();if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&s.shake)c.translate(Math.sin(t*80)*s.shake,Math.cos(t*95)*s.shake*.4);
 if(this.background.complete&&this.background.naturalWidth)c.drawImage(this.background,0,0,960,500);else{c.fillStyle='#102534';c.fillRect(0,0,960,500);}c.fillStyle='#07152338';c.fillRect(0,0,960,500);
 for(const a of s.actors){c.fillStyle='#020a1466';c.beginPath();c.ellipse(a.x,398,70,14,0,0,Math.PI*2);c.fill();}
 for(const e of s.effects.filter(e=>e.type==='zone'||e.type==='dash'))this.drawEffect(e);
 for(const a of [...s.actors].sort((a,b)=>a.x-b.x))this.drawActor(a);
 for(const e of s.effects.filter(e=>e.type!=='zone'&&e.type!=='dash'))this.drawEffect(e);
 for(const p of s.projectiles)this.drawProjectile(p);
 for(const n of s.numbers){const age=t-n.start;c.globalAlpha=1-age/.9;c.font='bold 29px system-ui';c.textAlign='center';c.lineWidth=5;c.strokeStyle='#06101b';c.strokeText(n.value,n.x,205-age*65);c.fillStyle=n.color;c.fillText(n.value,n.x,205-age*65);c.globalAlpha=1;}
 c.restore();this.drawHUD();if(!this.loaded){c.fillStyle='#071523b8';c.fillRect(0,0,960,500);c.fillStyle='#e2edff';c.textAlign='center';c.font='20px system-ui';c.fillText(this.failed?'角色素材暫時無法載入':'正在載入角色動作…',480,245);}
 if(s.winner!==null){c.fillStyle='#081424aa';c.fillRect(300,120,360,70);c.fillStyle='#ffe4a4';c.font='bold 28px system-ui';c.textAlign='center';c.fillText(s.winner===0?'VICTORY · 演示勝利':'DEFEAT · 演示落敗',480,162);}
 }
 drawActor(a){if(!this.loaded)return;const c=this.ctx,t=this.sim.time,pose=a.hp?a.pose:5;const sx=pose*256,sy=a.kind*(1024/3),sw=256,sh=1024/3;const breathing=a.hp&&pose===0?Math.sin(t*2.4+a.x)*2:0;c.save();c.translate(a.x,400+breathing);c.scale(a.facing,1);if(a.rootUntil>t)c.globalAlpha=.85;c.drawImage(this.atlas,sx,sy,sw,sh,-112,-278,224,299);c.restore();}
 drawHUD(){const c=this.ctx;for(let i=0;i<2;i++){const a=this.sim.actors[i],x=i?605:30;c.fillStyle='#071523cc';c.fillRect(x,18,325,61);c.fillStyle=i?'#ec9292':'#99e4d8';c.fillRect(x+12,48,300*a.hp/a.maxHP,10);if(a.shield){c.fillStyle='#c5ecff';c.fillRect(x+12+300*a.hp/a.maxHP,48,Math.min(300*(1-a.hp/a.maxHP),a.shield*.3),10);}c.strokeStyle='#d5e0ee66';c.strokeRect(x+12,48,300,10);c.fillStyle='#e5edfa';c.font='bold 15px system-ui';c.textAlign='left';c.fillText(this.names?.[i]||['玩家','對手'][i],x+12,39);c.font='10px system-ui';c.fillStyle='#b5c9dc';c.fillText(Math.round(a.hp)+' / 1000 · '+battlePrototypeNames[a.kind],x+12,71);}}
 glow(color,width=3){const c=this.ctx;c.strokeStyle=color;c.fillStyle=color;c.lineWidth=width;c.shadowColor=color;c.shadowBlur=20;}
 drawEffect(e){const c=this.ctx,t=this.sim.time,age=t-e.start,p=Math.min(1,age/(e.end-e.start)),x=e.actor?e.actor.x:e.x,y=290;c.save();this.glow(e.color);c.globalAlpha=Math.sin(Math.PI*p)*.95;
 if(e.type==='charge'){c.beginPath();c.arc(x,y,15+p*25,0,Math.PI*2);c.stroke();}
 if(e.type==='impact'||e.type==='blast'){for(let i=0;i<12;i++){const ang=i*Math.PI/6,dist=p*(e.type==='blast'?115:60);c.beginPath();c.moveTo(x+Math.cos(ang)*dist*.4,y+Math.sin(ang)*dist*.4);c.lineTo(x+Math.cos(ang)*dist,y+Math.sin(ang)*dist);c.stroke();}c.beginPath();c.arc(x,y,p*65,0,Math.PI*2);c.stroke();}
 if(e.type==='zone'){c.beginPath();c.ellipse(x,390,110,28,0,0,Math.PI*2);c.stroke();c.globalAlpha=.18;c.fill();}
 if(e.type==='shield'){c.beginPath();c.ellipse(x,292,83,120,0,0,Math.PI*2);c.stroke();c.globalAlpha=.11;c.fill();}
 if(e.type==='beam'){c.lineWidth=32*Math.sin(Math.PI*p);c.beginPath();c.moveTo(x,275);c.lineTo(e.to,275);c.stroke();c.shadowBlur=0;c.strokeStyle='#fff';c.lineWidth=8;c.stroke();}
 if(e.type==='slash'||e.type==='spin'){c.lineWidth=9;for(let i=0;i<3;i++){c.beginPath();c.ellipse(x,310,90+i*8,75+i*4,t*16+i,-1.6,1.2);c.stroke();}}
 if(e.type==='sword'){const yy=40+p*340;c.fillStyle='#fff2ba';c.beginPath();c.moveTo(x-16,yy-220);c.lineTo(x+16,yy-220);c.lineTo(x+10,yy-15);c.lineTo(x,yy);c.lineTo(x-10,yy-15);c.closePath();c.fill();c.fillRect(x-55,yy-190,110,10);}
 if(e.type==='dash'){c.lineWidth=28;c.beginPath();c.moveTo(e.x,315);c.lineTo(e.to,315);c.stroke();}
 c.restore();}
 drawProjectile(p){const c=this.ctx,t=this.sim.time;c.save();this.glow(p.color,5);c.translate(p.x,275+Math.sin(t*12)*3);if(p.type==='heart'){c.rotate(-Math.PI/4);c.fillRect(-12,-12,24,24);c.beginPath();c.arc(0,-12,12,Math.PI,0);c.arc(12,0,12,-Math.PI/2,Math.PI/2);c.fill();}else{c.beginPath();c.ellipse(0,0,p.type==='bolt'?32:17,p.type==='bolt'?7:17,0,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.shadowBlur=0;c.beginPath();c.arc(0,0,6,0,Math.PI*2);c.fill();}c.restore();}
}
function initLeagueStage(){
 const hero=document.querySelector('.hero-main');hero.insertAdjacentHTML('beforeend','<section class="league-battle" aria-label="英雄戰鬥展示"><div class="battle-heading"><div><span>CHAMPION COMBAT LAB</span><h2>走位、連招，讓技能真正打出去。</h2></div><button id="duel-auto" type="button" aria-pressed="false">自動對戰</button></div><div class="battle-canvas-wrap"><canvas id="battle-canvas" aria-label="原創角色動畫與技能戰鬥舞台" tabindex="0"></canvas></div><div class="battle-toolbar"><label>演示對手<select id="duel-opponent"></select></label><button id="duel-select" type="button">英雄／造型</button><button id="battle-basic" type="button">普攻 · A</button><button id="battle-reset" type="button">重新對戰</button><label class="battle-demo"><input id="battle-demo" type="checkbox" checked> 自由展示所有技能</label></div><div id="duel-skills" class="battle-skills"></div><p id="duel-status" role="status" aria-live="polite">正在載入角色動作…</p><p id="battle-prototype" class="battle-note"></p><p class="battle-note">點選地面走位 · 舞台聚焦時可按 A / Q / W / E / R · HP、傷害與勝負僅為動畫模擬，不產生競賽積分。</p><div class="duel-study"><button id="duel-due" type="button">到期複習</button><button id="duel-missed" type="button">錯題挑戰</button></div></section>');
 const select=document.querySelector('#duel-opponent');select.innerHTML=leagueChampions.map(c=>'<option value="'+c.id+'">'+escapeQuiz(c.name+' · '+c.id)+'</option>').join('');select.value=leagueOpponent;select.onchange=e=>{leagueOpponent=e.target.value;renderLeagueStage(true);};
 document.querySelector('#duel-select').onclick=()=>document.querySelector('#league-dialog').showModal();document.querySelector('#battle-reset').onclick=()=>renderLeagueStage(true);document.querySelector('#duel-due').onclick=()=>startGamePractice('all','due');document.querySelector('#duel-missed').onclick=()=>startGamePractice('all','missed');
 document.querySelector('#battle-demo').onchange=e=>{battleDemo=e.target.checked;if(!battleDemo&&battleRenderer)battleRenderer.sim.auto=false;renderLeagueStage();};
 document.querySelector('#duel-auto').onclick=()=>{const s=battleRenderer.sim;if(s.winner!==null)renderLeagueStage(true);battleRenderer.sim.auto=!battleRenderer.sim.auto;};document.querySelector('#battle-basic').onclick=()=>{battleRenderer.canvas.focus();battleRenderer.sim.cast(-1);};
 const canvas=document.querySelector('#battle-canvas');canvas.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;const key=e.key.toLowerCase(),i=['q','w','e','r'].indexOf(key);if(key==='a'){e.preventDefault();battleRenderer.sim.cast(-1);}else if(i>=0){e.preventDefault();castLeagueSkill(i);}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&battleRenderer)battleRenderer.sim.auto=false;});battleRenderer=new BattleCanvas(canvas);
}
function cancelLeagueDuel(){if(battleRenderer)battleRenderer.sim.auto=false;}
function renderLeagueStage(force=false){if(!battleRenderer)return;const {champion,skin,level}=leagueSelected(),enemy=leagueChampions.find(c=>c.id===leagueOpponent)||leagueChampions[0],key=champion.id+'_'+skin.num+'_'+enemy.id;
 if(force||battleRenderer.key!==key){battleRenderer.key=key;battleRenderer.sim.reset(battleKind(champion),battleKind(enemy));battleRenderer.names=[champion.name,enemy.name];}
 battleRenderer.sim.allowedSkills=battleDemo?[-1,0,1,2,3]:[-1,...leagueSkillLevels.map((n,i)=>level>=n?i:-1).filter(i=>i>=0)];
 document.querySelector('#battle-prototype').textContent='動畫原型：'+battlePrototypeNames[battleKind(champion)]+' vs '+battlePrototypeNames[battleKind(enemy)]+'。173 位英雄共用三種原創動畫；收藏造型使用官方插畫，舞台目前不還原每款服裝。';
 document.querySelector('#duel-skills').innerHTML=leagueSkillLevels.map((n,i)=>'<button type="button" data-battle-skill="'+i+'" '+(!battleDemo&&level<n?'disabled':'')+'><kbd>'+['Q','W','E','R'][i]+'</kbd><b>'+escapeQuiz(champion.skills[i])+'</b><small>施放</small><span>'+battleSkillFX[battleKind(champion)][i]+'</span></button>').join('');document.querySelectorAll('[data-battle-skill]').forEach(b=>b.onclick=()=>{battleRenderer.canvas.focus();castLeagueSkill(Number(b.dataset.battleSkill));});
}
function animateLeagueDuel(index){if(!battleRenderer||!battleRenderer.loaded)return false;if(!battleDemo&&leagueLevel()<leagueSkillLevels[index])return false;return battleRenderer.sim.cast(index);}
