/* Playable local MOBA prototype. This simulation never writes learning or ladder scores. */
const MOBA_HEROES={
 Zed:{name:'劫',hp:1200,resource:200,regen:30,speed:190,damage:68,cost:[70,40,45,0],cooldown:[5,12,4,22],skills:['風魔手裡劍','疾風殘影','影斬','死亡印記'],tips:['瞄準直線；本體與影分身一起投射，可穿過小兵。','放置影分身；再次施放 W 即可交換位置。','本體與影分身周遭斬擊、緩速，需要靠近目標。','點選敵方英雄，突襲並標記；3 秒後依期間傷害引爆。']},
 Naafiri:{name:'娜菲芮',hp:1350,resource:400,regen:14,speed:195,damage:64,cost:[55,60,45,80],cooldown:[6,15,7,22],skills:['冥血匕首','獵犬嚎殺','開膛破肚','尋血獵犬'],tips:['直線匕首命中造成流血；3 秒內可再次投射。','短暫無法被指定，召喚額外獵犬並加速、提高攻擊。','向指定方向衝刺，沿途傷害並召回、治療獵犬。','點敵方英雄蓄力突進；參與擊殺可再次施放，第二次獲得護盾。']}
};
function mobaDirection(angle){return ((Math.round(angle/(Math.PI/4))%8)+8)%8;}
const mobaDistance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),mobaClamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const MOBA_ROCKS=[{x:385,y:205,r:63},{x:970,y:450,r:63},{x:770,y:128,r:44},{x:612,y:624,r:42}];
function mobaWalkable(p,r=15){return p.x>=35+r&&p.x<=1245-r&&p.y>=70+r&&p.y<=660-r&&!MOBA_ROCKS.some(o=>mobaDistance(p,o)<o.r+r);}
function mobaLineOpen(a,b){const d=mobaDistance(a,b);for(let i=0;i<=Math.ceil(d/18);i++){const k=i/Math.max(1,Math.ceil(d/18));if(!mobaWalkable({x:a.x+(b.x-a.x)*k,y:a.y+(b.y-a.y)*k}))return false;}return true;}
function mobaPath(a,dest){
 const goal={x:mobaClamp(dest.x,55,1225),y:mobaClamp(dest.y,90,640)};
 if(!mobaWalkable(goal))return [];if(mobaLineOpen(a,goal))return [goal];
 const size=30,key=p=>p.x+','+p.y,point=p=>({x:p.x*size+55,y:p.y*size+90}),grid=p=>({x:Math.round((p.x-55)/size),y:Math.round((p.y-90)/size)}),start=grid(a),end=grid(goal),open=[start],seen=new Map([[key(start),{g:0,parent:null}]]);
 let found=null,steps=0;
 while(open.length&&steps++<1200){open.sort((a,b)=>(seen.get(key(a)).g+Math.hypot(a.x-end.x,a.y-end.y))-(seen.get(key(b)).g+Math.hypot(b.x-end.x,b.y-end.y)));const n=open.shift();if(key(n)===key(end)){found=n;break;}
  for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const v={x:n.x+dx,y:n.y+dy},p=point(v);if(!mobaWalkable(p)||!mobaLineOpen(point(n),p))continue;const g=seen.get(key(n)).g+Math.hypot(dx,dy),old=seen.get(key(v));if(!old||g<old.g){seen.set(key(v),{g,parent:n});if(!open.some(o=>key(o)===key(v)))open.push(v);}}
 }
 if(!found)return [];const path=[goal];for(let p=found;p&&key(p)!==key(start);p=seen.get(key(p)).parent)path.unshift(point(p));return path;
}
function mobaSegmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,k=mobaClamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return mobaDistance(p,{x:a.x+dx*k,y:a.y+dy*k});}
class MobaSimulation{
 constructor(champion='Zed'){this.reset(champion);}
 reset(champion='Zed',practice=this.practice||false){
  if(!MOBA_HEROES[champion])champion='Zed';this.time=0;this.serial=0;this.running=false;this.paused=false;this.winner=null;this.units=[];this.events=[];this.projectiles=[];this.fx=[];this.numbers=[];this.shadows=[];this.marks=[];this.bleeds=[];this.nextWave=1;this.wave=0;this.auto=false;this.kills=[0,0];this.log='選擇英雄，開始對局；推倒敵塔後摧毀主堡。';
  this.heroes=[this.hero(champion,0),this.hero(champion==='Zed'?'Naafiri':'Zed',1)];this.units.push(...this.heroes);
  this.towers=[this.unit('tower',0,365,445,1800),this.unit('tower',1,945,220,1800)];this.nexuses=[this.unit('nexus',0,130,590,2200),this.unit('nexus',1,1160,120,2200)];this.units.push(...this.towers,...this.nexuses);
  for(const h of this.heroes)if(h.champion==='Naafiri')this.spawnPack(h,2);
  this.practice=practice;this.unlimited=this.unlimited||false;this.training={damage:0,hits:0,first:null};
  if(practice){const h=this.heroes[0],dummy=this.heroes[1];Object.assign(h,{x:480,y:400,gold:1500});Object.assign(dummy,{x:700,y:320,hp:10000,maxHP:10000,dummy:true});this.units=this.units.filter(u=>u.ownerId!==dummy.id);this.log='練習假人不反擊；瞄準假人練習 QWER 與連招。';}
 }
 refreshPractice(){if(!this.practice)return false;const active=this.running,paused=this.paused;this.reset(this.heroes[0].champion,true);this.running=active;this.paused=paused;return true;}
 unit(type,team,x,y,hp){return {id:++this.serial,type,team,x,y,hp,maxHP:hp,r:type==='tower'?30:type==='nexus'?40:14,attackAt:0,pose:0,poseUntil:0,path:[],targetId:null,damage:type==='tower'?150:30,speed:80,range:type==='tower'?245:40,shield:0,shieldUntil:0,slowUntil:0,invulnerableUntil:0,facing:team?Math.PI:0};}
 hero(champion,team){const d=MOBA_HEROES[champion],u=this.unit('hero',team,team?995:285,team?225:505,d.hp);return Object.assign(u,{champion,speed:d.speed,damage:d.damage,range:champion==='Zed'?80:95,resource:d.resource,maxResource:d.resource,regen:d.regen,cooldowns:[0,0,0,0],busyUntil:0,respawnAt:0,gold:0,xp:0,level:1,cs:0,items:[],flashAt:0,healAt:0,aiAt:0,packAt:0,passiveAt:0});}
 start(){if(this.winner!==null)return;this.running=true;this.log=this.practice?'練習開始！瞄準假人試放 QWER；可開啟無冷卻／無限資源。':'對局開始！右鍵移動，左鍵攻擊；QWER 瞄準施法。';}
 find(id){return this.units.find(u=>u.id===id);}
 later(delay,fn){this.events.push({at:this.time+delay,fn});}
 effect(type,x,y,duration=.55,extra={}){this.fx.push({type,x,y,start:this.time,end:this.time+duration,...extra});}
 pose(u,frame,duration){u.pose=frame;u.poseUntil=this.time+duration;}
 enemies(u){return this.units.filter(v=>v.team!==u.team&&v.hp>0&&v.invulnerableUntil<=this.time);}
 targetAt(p,team=0){return this.units.filter(u=>u.team!==team&&u.hp>0&&u.invulnerableUntil<=this.time&&mobaDistance(u,p)<u.r+24).sort((a,b)=>mobaDistance(a,p)-mobaDistance(b,p))[0];}
 command(p,attackMove=false){const h=this.heroes[0];if(!this.running||this.paused||!h.hp||this.winner!==null)return false;h.recallAt=0;h.targetId=null;h.path=mobaPath(h,p);h.attackMove=attackMove;this.effect('move',p.x,p.y,.7);return h.path.length>0;}
 attackTarget(target){const h=this.heroes[0];if(!target||target.team===h.team||!target.hp||!this.running||this.paused||!h.hp)return false;h.recallAt=0;h.targetId=target.id;h.attackMove=false;h.path=[];return true;}
 stop(){const h=this.heroes[0];h.targetId=null;h.path=[];h.recallAt=0;h.attackMove=false;}
 spawnPack(h,count,extra=false){for(let i=0;i<count;i++){const u=this.unit('hound',h.team,h.x+Math.cos(i*2.2)*45,h.y+Math.sin(i*2.2)*45,180);Object.assign(u,{champion:'Naafiri',ownerId:h.id,speed:235,damage:17,range:38,expireAt:extra?this.time+8:Infinity});this.units.push(u);}}
 spawnWave(){this.wave++;for(let team=0;team<2;team++)for(let i=0;i<4;i++){const u=this.unit('minion',team,team?1100+i*12:180-i*12,team?162+i*12:563-i*12, i===3?210:280);u.ranged=i===3;u.range=u.ranged?150:36;u.damage=u.ranged?24:30;u.speed=72;this.units.push(u);}this.nextWave=this.time+12;}
 reward(source,target){const owner=source?.type==='hero'?source:this.find(source?.ownerId);if(!owner||owner.type!=='hero')return;const gain=target.type==='hero'?180:target.type==='tower'?150:target.type==='minion'?25:0;owner.gold+=gain;owner.xp+=target.type==='hero'?180:target.type==='minion'?35:80;if(target.type==='minion')owner.cs++;const lv=Math.min(18,1+Math.floor(owner.xp/180));while(owner.level<lv){owner.level++;owner.maxHP+=60;owner.hp=Math.min(owner.maxHP,owner.hp+60);owner.damage+=4;this.effect('level',owner.x,owner.y,1.2);}}
 damage(target,amount,source,kind='hit'){
  if(!target?.hp||target.invulnerableUntil>this.time||this.winner!==null)return 0;
  if(target.type==='nexus'&&this.towers[target.team].hp>0)return 0;
  const absorbed=Math.min(target.shield||0,amount);target.shield-=absorbed;const value=Math.min(target.hp,Math.max(0,amount-absorbed));target.hp=Math.max(0,target.hp-value);target.recallAt=0;this.pose(target,target.hp?6:7,.22);this.numbers.push({x:target.x,y:target.y-70,value:Math.round(value),start:this.time,end:this.time+.75});this.effect(kind,target.x,target.y,.4,{team:source?.team||0});
  for(const mark of this.marks)if(mark.targetId===target.id&&mark.sourceId===source?.id&&!mark.exploding)mark.stored+=value;
  if(target.dummy){const owner=source?.type==='hero'?source:this.find(source?.ownerId);if(owner?.id===this.heroes[0].id&&value>0){this.training.damage+=value;this.training.hits++;if(this.training.first===null)this.training.first=this.time;}if(!target.hp){target.hp=target.maxHP;this.log='假人生命已自動恢復，傷害統計持續累計。';}return value;}
  if(!this.practice&&source?.type==='hero'&&target.type==='hero'){const tower=this.towers[target.team];if(tower.hp&&mobaDistance(tower,source)<tower.range){tower.targetId=source.id;tower.aggroUntil=this.time+3;}}
  if(!target.hp){this.reward(source,target);if(target.type==='hero'){this.kills[1-target.team]++;target.respawnAt=this.time+7;target.path=[];target.targetId=null;this.units.filter(u=>u.ownerId===target.id).forEach(u=>u.hp=0);this.shadows=this.shadows.filter(s=>s.ownerId!==target.id);this.log=(target.team?'敵方':'我方')+'英雄倒下，7 秒後復活。';const killer=source?.type==='hero'?source:this.find(source?.ownerId);if(killer?.champion==='Naafiri'&&killer.pursuitUntil>this.time){killer.pursuitRecast=true;killer.cooldowns[3]=this.time;}}
   if(target.type==='tower')this.log=(target.team?'敵方':'我方')+'防禦塔已摧毀，主堡現在可受傷害！';
   if(target.type==='nexus'){this.winner=1-target.team;this.running=false;this.log=this.winner===0?'VICTORY · 已摧毀敵方主堡':'DEFEAT · 我方主堡被摧毀';}
  }return value;
 }
 projectile(source,point,opts={}){const d=mobaDistance(source,point)||1,range=opts.range||630;this.projectiles.push({x:source.x,y:source.y,vx:(point.x-source.x)/d*(opts.speed||720),vy:(point.y-source.y)/d*(opts.speed||720),left:range,sourceId:source.id,team:source.team,damage:opts.damage||100,type:opts.type||'shuriken',radius:opts.radius||12,pierce:opts.pierce!==false,hits:[],...opts});}
 canCast(h,i){return this.running&&!this.paused&&this.winner===null&&h.hp>0&&this.time>=h.busyUntil&&h.cooldowns[i]<=this.time;}
 cast(i,point,side=0){
  const h=this.heroes[side],d=MOBA_HEROES[h.champion];if(!Number.isInteger(i)||i<0||i>3||!this.canCast(h,i))return false;
  point=point||{x:h.x+250,y:h.y};const shadow=this.shadows.find(s=>s.ownerId===h.id&&s.swap&&s.end>this.time),qRecast=h.champion==='Naafiri'&&i===0&&h.qRecastUntil>this.time,wSwap=h.champion==='Zed'&&i===1&&shadow;
  const target=i===3?this.targetAt(point,h.team):null;
  if(i===3&&(!target||target.type!=='hero'||mobaDistance(h,target)>540)){if(!side)this.log='R 需要點選 540 距離內的敵方英雄。';return false;}
  const cost=qRecast||wSwap?0:d.cost[i];if(h.resource<cost){if(!side)this.log='能量／魔力不足，等待恢復。';return false;}
  h.resource-=cost;h.recallAt=0;h.path=[];h.busyUntil=this.time+.14;this.pose(h,5,.4);h.facing=Math.atan2(point.y-h.y,point.x-h.x);
  h.cooldowns[i]=this.time+d.cooldown[i];this.log=(side?'敵方':'玩家')+' · '+d.skills[i];
  if(h.champion==='Zed'){
   if(i===0){const origins=[h,...this.shadows.filter(s=>s.ownerId===h.id&&s.end>this.time)];for(const origin of origins)this.projectile({...origin,id:h.id,team:h.team},point,{damage:115+h.damage*.45,type:'shuriken',range:660});}
   if(i===1){if(wSwap){const old={x:h.x,y:h.y};h.x=shadow.x;h.y=shadow.y;shadow.x=old.x;shadow.y=old.y;shadow.swap=false;h.cooldowns[1]=shadow.originalCooldown;this.effect('dash',h.x,h.y,.45,{from:old});}else{const dist=mobaDistance(h,point),k=Math.min(1,330/(dist||1)),p={x:h.x+(point.x-h.x)*k,y:h.y+(point.y-h.y)*k};if(!mobaWalkable(p)){h.resource+=cost;h.cooldowns[i]=this.time;return false;}this.shadows.push({...p,ownerId:h.id,team:h.team,champion:'Zed',end:this.time+5,swap:true,originalCooldown:this.time+d.cooldown[1]});h.cooldowns[1]=this.time+.35;this.effect('shadow',p.x,p.y,.7);}}
   if(i===2){const hit=new Set();for(const origin of [h,...this.shadows.filter(s=>s.ownerId===h.id)]){this.effect('slash',origin.x,origin.y,.55,{radius:130,team:h.team});for(const u of this.enemies(h))if(mobaDistance(origin,u)<130+u.r&&!hit.has(u.id)){hit.add(u.id);this.damage(u,90+h.damage*.6,h);u.slowUntil=this.time+1.2;}}}
   if(i===3){const old={x:h.x,y:h.y};h.invulnerableUntil=this.time+.6;this.shadows.push({...old,ownerId:h.id,team:h.team,champion:'Zed',end:this.time+5,swap:false});this.later(.45,()=>{if(!h.hp||!target.hp)return;const ang=Math.atan2(target.y-h.y,target.x-h.x),p={x:target.x+Math.cos(ang)*75,y:target.y+Math.sin(ang)*75};if(mobaWalkable(p)){h.x=p.x;h.y=p.y;}h.targetId=target.id;this.marks.push({targetId:target.id,sourceId:h.id,end:this.time+3,stored:0});this.effect('mark',target.x,target.y,3,{targetId:target.id});});}
  }else{
   if(i===0){this.projectile(h,point,{type:'dagger',damage:95+h.damage*.5,bleed:true,range:620});if(qRecast){h.qRecastUntil=0;}else{h.qRecastUntil=this.time+3;h.qOriginalCooldown=this.time+d.cooldown[0];h.cooldowns[0]=this.time+.4;}if(qRecast)h.cooldowns[0]=h.qOriginalCooldown;}
   if(i===1){h.invulnerableUntil=this.time+.7;h.empoweredUntil=this.time+8;this.spawnPack(h,3,true);this.effect('howl',h.x,h.y,1,{team:h.team});}
   if(i===2){const old={x:h.x,y:h.y},dist=mobaDistance(h,point),k=Math.min(1,260/(dist||1)),end={x:h.x+(point.x-h.x)*k,y:h.y+(point.y-h.y)*k};if(mobaLineOpen(h,end)){h.x=end.x;h.y=end.y;}this.effect('dash',h.x,h.y,.6,{from:old,team:h.team});for(const u of this.enemies(h))if(mobaSegmentDistance(u,old,h)<60+u.r)this.damage(u,100+h.damage*.4,h);this.units.filter(u=>u.ownerId===h.id&&u.hp>0).forEach(u=>{u.x=h.x-35;u.y=h.y+20;u.hp=u.maxHP;});}
   if(i===3){const second=h.pursuitRecast;h.pursuitRecast=false;h.pursuitUntil=this.time+7;this.effect('target',target.x,target.y,.65,{targetId:target.id});h.busyUntil=this.time+.55;this.later(.45,()=>{if(!h.hp||!target.hp)return;const old={x:h.x,y:h.y},p={x:target.x+(h.team?60:-60),y:target.y+20};if(mobaWalkable(p)){h.x=p.x;h.y=p.y;}h.targetId=target.id;this.effect('dash',h.x,h.y,.6,{from:old,team:h.team});this.damage(target,150+h.damage*.7,h);if(second){h.shield=220;h.shieldUntil=this.time+4;}this.units.filter(u=>u.ownerId===h.id&&u.hp>0).forEach(u=>{u.x=h.x;u.y=h.y;u.targetId=target.id;});});}
  }return true;
 }
 attack(u,v){if(!v?.hp||u.attackAt>this.time||v.invulnerableUntil>this.time||u.type==='hero'&&u.busyUntil>this.time)return;u.attackAt=this.time+(u.type==='tower'?1.05:u.type==='hound'?.85:.8);u.facing=Math.atan2(v.y-u.y,v.x-u.x);this.pose(u,3,.16);this.later(.16,()=>{if(!u.hp||!v.hp||this.winner!==null)return;this.pose(u,4,.24);let damage=u.damage+(u.empoweredUntil>this.time?25:0);if(u.champion==='Zed'&&u.type==='hero'&&v.hp<v.maxHP*.5&&u.passiveAt<=this.time){damage+=v.maxHP*.06;u.passiveAt=this.time+8;}
  if(u.type==='tower'||u.ranged){this.projectiles.push({x:u.x,y:u.y,vx:0,vy:0,left:1000,sourceId:u.id,team:u.team,damage,type:u.type==='tower'?'tower':'bolt',radius:6,targetId:v.id,speed:u.type==='tower'?620:440,pierce:false,hits:[]});}else if(mobaDistance(u,v)<=u.range+v.r+35){this.damage(v,damage,u,'slash');if(u.type==='hero')this.effect('slash',v.x,v.y,.35,{radius:48,team:u.team});}
 });}
 moveUnit(u,goal,dt){if(!goal)return;const dx=goal.x-u.x,dy=goal.y-u.y,d=Math.hypot(dx,dy);if(d<4)return;u.facing=Math.atan2(dy,dx);const speed=u.speed*(u.slowUntil>this.time?.55:1)*(u.empoweredUntil>this.time?1.28:1),step=Math.min(d,speed*dt),p={x:u.x+dx/d*step,y:u.y+dy/d*step};if(mobaWalkable(p,u.type==='hero'?15:8)){u.x=p.x;u.y=p.y;if(this.time>=u.poseUntil)u.pose=1;}else{const px={x:p.x,y:u.y},py={x:u.x,y:p.y};if(mobaWalkable(px))u.x=px.x;else if(mobaWalkable(py))u.y=py.y;}}
 nearest(u,r,types){return this.enemies(u).filter(v=>(!types||types.includes(v.type))&&mobaDistance(u,v)<r).sort((a,b)=>mobaDistance(u,a)-mobaDistance(u,b))[0];}
 heroAI(h){if(this.time<h.aiAt||!h.hp)return;h.aiAt=this.time+.35;const base=this.nexuses[h.team];if(h.hp<h.maxHP*.25){h.targetId=null;h.path=mobaPath(h,base);return;}
  const threat=this.nearest(h,420,['hero']);if(threat){h.targetId=threat.id;h.path=[];const i=h.champion==='Zed'?(mobaDistance(h,threat)<125?2:this.time%11<4?1:0):(mobaDistance(h,threat)<180?2:this.time%10<3?1:0);this.cast(i,threat,h.team);if(threat.hp<threat.maxHP*.65)this.cast(3,threat,h.team);return;}
  const v=this.nearest(h,430,['minion','hound'])|| (this.towers[1-h.team].hp?this.towers[1-h.team]:this.nexuses[1-h.team]);h.targetId=v?.id;
 }
 flash(point){const h=this.heroes[0];if(!this.running||this.paused||!h.hp||h.flashAt>this.time)return false;const old={x:h.x,y:h.y},d=mobaDistance(h,point),k=Math.min(1,210/(d||1)),p={x:h.x+(point.x-h.x)*k,y:h.y+(point.y-h.y)*k};if(!mobaWalkable(p))return false;h.x=p.x;h.y=p.y;h.path=[];h.flashAt=this.time+30;this.effect('flash',p.x,p.y,.6,{from:old});return true;}
 heal(){const h=this.heroes[0];if(!this.running||this.paused||!h.hp||h.healAt>this.time)return false;h.hp=Math.min(h.maxHP,h.hp+260);h.healAt=this.time+25;this.effect('heal',h.x,h.y,.8);return true;}
 recall(){const h=this.heroes[0];if(!this.running||this.paused||!h.hp)return;h.path=[];h.targetId=null;h.recallAt=this.time+3;this.effect('recall',h.x,h.y,3);}
 buy(item){const h=this.heroes[0],defs={sword:{cost:350,damage:20},health:{cost:400,hp:180},boots:{cost:300,speed:35}},d=defs[item];if(!d||!h.hp||h.items.length>=3||h.gold<d.cost||mobaDistance(h,this.nexuses[0])>170)return false;h.gold-=d.cost;h.items.push(item);h.damage+=d.damage||0;h.speed+=d.speed||0;if(d.hp){h.maxHP+=d.hp;h.hp+=d.hp;}return true;}
 step(dt){
  if(!this.running||this.paused||this.winner!==null)return;dt=mobaClamp(dt,0,.05);this.time+=dt;const due=this.events.filter(e=>e.at<=this.time);this.events=this.events.filter(e=>e.at>this.time);due.forEach(e=>e.fn());
  if(!this.practice&&this.time>=this.nextWave&&this.units.filter(u=>u.type==='minion'&&u.hp>0).length<40)this.spawnWave();
  for(const s of this.shadows)if(s.swap&&s.end<=this.time){const h=this.find(s.ownerId);if(h)h.cooldowns[1]=Math.max(h.cooldowns[1],s.originalCooldown);}
  this.shadows=this.shadows.filter(s=>s.end>this.time&&this.find(s.ownerId)?.hp);
  for(const mark of this.marks.filter(m=>m.end<=this.time)){const target=this.find(mark.targetId),source=this.find(mark.sourceId);mark.exploding=true;this.damage(target,100+mark.stored*.35,source,'mark');}this.marks=this.marks.filter(m=>m.end>this.time);
  for(const b of this.bleeds){const v=this.find(b.targetId);if(b.tickAt<=this.time&&v?.hp){this.damage(v,12,this.find(b.sourceId),'bleed');b.tickAt=this.time+.5;}}this.bleeds=this.bleeds.filter(b=>b.end>this.time&&this.find(b.targetId)?.hp);
  for(const h of this.heroes){if(h.dummy)continue;if(!h.hp){if(this.time>=h.respawnAt){h.x=this.nexuses[h.team].x+(h.team?-60:60);h.y=this.nexuses[h.team].y+(h.team?40:-40);h.hp=h.maxHP;h.resource=h.maxResource;h.shield=0;h.pose=0;h.busyUntil=0;h.recallAt=0;h.qRecastUntil=0;h.pursuitRecast=false;if(h.champion==='Naafiri')this.spawnPack(h,2);}continue;}
   if(this.practice&&this.unlimited){h.resource=h.maxResource;h.cooldowns.fill(this.time);h.flashAt=this.time;h.healAt=this.time;}
   h.resource=Math.min(h.maxResource,h.resource+h.regen*dt);h.gold+=dt*2;
   if(h.qRecastUntil&&h.qRecastUntil<=this.time){h.cooldowns[0]=Math.max(h.cooldowns[0],h.qOriginalCooldown||0);h.qRecastUntil=0;}
   if(h.packTarget&&!this.find(h.packTarget)?.hp)h.packTarget=null;
   if(mobaDistance(h,this.nexuses[h.team])<150){h.hp=Math.min(h.maxHP,h.hp+120*dt);h.resource=Math.min(h.maxResource,h.resource+60*dt);}else h.hp=Math.min(h.maxHP,h.hp+.7*dt);
   if(h.recallAt&&this.time>=h.recallAt){const base=this.nexuses[h.team];h.x=base.x+(h.team?-50:50);h.y=base.y+(h.team?25:-25);h.recallAt=0;}
   if(h.champion==='Naafiri'&&this.time>=h.packAt){h.packAt=this.time+8;const count=this.units.filter(u=>u.hp&&u.ownerId===h.id&&!Number.isFinite(u.expireAt)).length;if(count<2)this.spawnPack(h,2-count);}
   if(!this.practice&&(h.team===1||this.auto))this.heroAI(h);
  }
  for(const u of this.units){if(!u.hp)continue;if(u.shieldUntil<this.time)u.shield=0;if(u.type==='hound'&&u.expireAt<=this.time){u.hp=0;continue;}if(this.time>=u.poseUntil)u.pose=0;
   if(u.type==='nexus'||u.dummy||this.practice&&u.type==='tower')continue;
   if(u.type==='tower'){let target=this.find(u.targetId);if(!target?.hp||mobaDistance(u,target)>u.range||u.aggroUntil<=this.time)target=this.nearest(u,u.range,['minion','hound'])||this.nearest(u,u.range,['hero']);u.targetId=target?.id;if(target)this.attack(u,target);continue;}
   if(u.type==='hero'&&(u.busyUntil>this.time||u.recallAt))continue;
   let target=this.find(u.targetId);if(target?.hp<=0||target?.invulnerableUntil>this.time)target=null;
   if(u.type==='hound'){const owner=this.find(u.ownerId);if(!owner?.hp){u.hp=0;continue;}target=this.find(owner.packTarget||owner.targetId);if(!target?.hp||target.invulnerableUntil>this.time)target=null;if(!target){const ang=u.id*2.1;this.moveUnit(u,{x:owner.x+Math.cos(ang)*45,y:owner.y+Math.sin(ang)*45},dt);continue;}}
   if(u.type==='minion')target=this.nearest(u,175,['minion','hound','hero'])||this.nearest(u,220,['tower','nexus']);
   if(u.type==='hero'&&!target&&u.attackMove)target=this.nearest(u,190,['hero','minion','hound']);
   if(target){u.targetId=target.id;if(mobaDistance(u,target)<u.range+target.r){this.attack(u,target);}else{if(u.type==='hero'){if(!u.path.length||mobaDistance(u.path.at(-1),target)>50)u.path=mobaPath(u,target);this.moveUnit(u,u.path[0],dt);if(u.path[0]&&mobaDistance(u,u.path[0])<8)u.path.shift();}else this.moveUnit(u,target,dt);}}
   else if(u.type==='hero'){if(u.path[0]){this.moveUnit(u,u.path[0],dt);if(mobaDistance(u,u.path[0])<8)u.path.shift();}}
   else if(u.type==='minion')this.moveUnit(u,this.towers[1-u.team].hp?this.towers[1-u.team]:this.nexuses[1-u.team],dt);
  }
  this.projectiles=this.projectiles.filter(p=>{const source=this.find(p.sourceId);if(p.targetId){const target=this.find(p.targetId);if(!target?.hp||target.invulnerableUntil>this.time)return false;const d=mobaDistance(p,target)||1;p.vx=(target.x-p.x)/d*(p.speed||600);p.vy=(target.y-p.y)/d*(p.speed||600);}
   const old={x:p.x,y:p.y};p.x+=p.vx*dt;p.y+=p.vy*dt;p.left-=Math.hypot(p.vx,p.vy)*dt;
   for(const u of this.units)if(u.hp&&u.team!==p.team&&u.invulnerableUntil<=this.time&&!p.hits.includes(u.id)&&(!p.targetId||u.id===p.targetId)&&mobaSegmentDistance(u,old,p)<u.r+p.radius){p.hits.push(u.id);let amount=p.damage;if(p.bleed){const b=this.bleeds.find(b=>b.targetId===u.id&&b.sourceId===p.sourceId);if(b){amount+=90;this.bleeds=this.bleeds.filter(v=>v!==b);}else this.bleeds.push({targetId:u.id,sourceId:p.sourceId,end:this.time+3,tickAt:this.time+.5});if(source?.champion==='Naafiri'&&u.type==='hero')source.packTarget=u.id;}
    this.damage(u,amount,source,p.type==='tower'?'towerHit':'hit');if(p.pierce)p.damage*=.7;else return false;}
   return p.left>0&&p.x>0&&p.x<1280&&p.y>30&&p.y<700;
  });
  // Separate moving bodies so units cannot completely stack.
  const bodies=this.units.filter(u=>u.hp&&['hero','minion','hound'].includes(u.type));for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],d=mobaDistance(a,b),r=a.r+b.r;if(d>0&&d<r){const k=(r-d)*.25/d,dx=(a.x-b.x)*k,dy=(a.y-b.y)*k;const pa={x:a.x+dx,y:a.y+dy},pb={x:b.x-dx,y:b.y-dy};if(!a.dummy&&mobaWalkable(pa))Object.assign(a,pa);if(!b.dummy&&mobaWalkable(pb))Object.assign(b,pb);}}
  this.fx=this.fx.filter(f=>f.end>this.time);this.numbers=this.numbers.filter(n=>n.end>this.time);this.units=this.units.filter(u=>u.hp||['hero','tower','nexus'].includes(u.type));
 }
}
let battleDemo=true,mobaRenderer=null;
class MobaCanvas{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.sim=new MobaSimulation();this.mouse={x:640,y:360};this.armed=null;this.quickCast=true;this.loaded=false;this.supported=true;this.visible=true;this.last=0;this.nextUI=0;
  this.atlas=new Image();this.directions=new Image();this.terrain=new Image();this.props=new Image();const ready=()=>{this.loaded=[this.atlas,this.directions,this.terrain,this.props].every(i=>i.complete&&i.naturalWidth>0);if(this.loaded){this.updateUI(true);this.message('戰場與角色已就緒。選擇對戰或練習，再按開始對局。');}};this.atlas.onload=ready;this.directions.onload=ready;this.terrain.onload=ready;this.props.onload=ready;const failed=()=>{this.assetError='戰場素材載入失敗，請重新整理。';this.message(this.assetError);};this.atlas.onerror=failed;this.directions.onerror=failed;this.terrain.onerror=failed;this.props.onerror=failed;this.atlas.src='assets/moba-zed-naafiri-v1.png';this.directions.src='assets/moba-directions-v2.png';this.terrain.src='assets/moba-terrain-v3.png';this.props.src='assets/moba-world-objects-v3.png';
  this.resize();new ResizeObserver(()=>this.resize()).observe(canvas);new IntersectionObserver(entries=>{this.visible=entries[0]?.isIntersecting!==false;if(!this.visible&&this.sim.running)this.sim.paused=true;}).observe(canvas);
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointermove',e=>{this.mouse=this.point(e);});canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus();const p=this.point(e),target=this.hitTest(p);this.mouse=p;if(!this.supported||!this.loaded)return;if(e.button===2){this.armed=null;this.sim.command(p);return;}if(this.armed!==null){const at=target?{x:target.x,y:target.y}:p;const ok=this.armed==='D'?this.sim.flash(at):this.armed==='A'?this.sim.command(p,true):this.sim.cast(this.armed,at);if(ok)this.armed=null;this.updateUI(true);return;}if(target)this.sim.attackTarget(target);else this.sim.command(p);});
  canvas.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase(),i=['q','w','e','r'].indexOf(k);if(i>=0){e.preventDefault();if(this.quickCast&&!e.shiftKey)this.quick(i);else this.arm(i);}else if(k==='a'||k==='d'){e.preventDefault();if(k==='d'&&this.quickCast&&!e.shiftKey)this.quick('D');else this.arm(k.toUpperCase());}else if(k==='f'){e.preventDefault();this.sim.heal();}else if(k==='b'){e.preventDefault();this.sim.recall();}else if(k==='s'){e.preventDefault();this.sim.stop();this.armed=null;}else if(k==='escape')this.armed=null;else if(k===' '){e.preventDefault();this.sim.paused=!this.sim.paused;}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.sim.running)this.sim.paused=true;});this.loop=this.loop.bind(this);requestAnimationFrame(this.loop);
 }
 resize(){this.ratio=Math.min(window.devicePixelRatio||1,2);this.canvas.width=1280*this.ratio;this.canvas.height=720*this.ratio;}
 point(e){const r=this.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*1280/r.width,y:(e.clientY-r.top)*720/r.height};}
 hitTest(p){return this.sim.units.filter(u=>u.team===1&&u.hp&&u.invulnerableUntil<=this.sim.time&&(mobaDistance(u,p)<u.r+22||u.type==='hero'&&Math.abs(p.x-u.x)<45&&p.y<u.y&&p.y>u.y-120||u.type==='minion'&&Math.abs(p.x-u.x)<20&&p.y<u.y&&p.y>u.y-55||['tower','nexus'].includes(u.type)&&Math.abs(p.x-u.x)<42&&p.y<u.y&&p.y>u.y-115)).sort((a,b)=>mobaDistance(a,p)-mobaDistance(b,p))[0];}
 message(text){const e=document.querySelector('#duel-status');if(e&&e.textContent!==text)e.textContent=text;}
 quick(i){if(!this.supported||!this.loaded)return false;const target=this.hitTest(this.mouse),point=target?{x:target.x,y:target.y}:this.mouse;const ok=i==='D'?this.sim.flash(point):this.sim.cast(i,point);if(ok)this.armed=null;this.updateUI(true);return ok;}
 arm(i){if(!this.supported||!this.sim.running||this.sim.paused||!this.sim.heroes[0].hp)return;this.armed=this.armed===i?null:i;this.updateUI(true);}
 loop(now){const dt=this.last?Math.min((now-this.last)/1000,.05):0;this.last=now;if(this.visible&&!document.hidden){this.sim.step(dt);this.draw();}if(now>=this.nextUI){this.updateUI();this.nextUI=now+120;}requestAnimationFrame(this.loop);}
 updateUI(force=false){const s=this.sim,h=s.heroes[0],d=MOBA_HEROES[h.champion],put=(id,t)=>{const e=document.querySelector('#'+id);if(e&&e.textContent!==t)e.textContent=t;};
  put('moba-training-stats','累積傷害 '+Math.round(s.training.damage)+' · 命中 '+s.training.hits+' · DPS '+(s.training.first===null?'0':Math.round(s.training.damage/Math.max(1,s.time-s.training.first))));const training=document.querySelector('#moba-training');if(training)training.hidden=!s.practice;const auto=document.querySelector('#moba-auto');if(auto){auto.disabled=s.practice;if(s.practice)auto.checked=false;}
  const portrait=document.querySelector('#moba-portrait');if(portrait){const url='https://ddragon.leagueoflegends.com/cdn/16.19.1/img/champion/'+h.champion+'.png';if(portrait.getAttribute('src')!==url){portrait.src=url;portrait.alt=d.name;}}
  put('moba-player',d.name+' · 對局 LV. '+h.level);put('moba-stats',Math.round(h.hp)+' / '+h.maxHP+' HP · '+Math.round(h.resource)+' / '+h.maxResource+(h.champion==='Zed'?' 能量':' 魔力')+'\n'+Math.floor(h.gold)+' G · '+h.cs+' 補刀 · 攻擊 '+Math.round(h.damage));
  const hp=document.querySelector('#moba-hp'),res=document.querySelector('#moba-resource');if(hp){hp.style.width=(h.hp/h.maxHP*100)+'%';res.style.width=(h.resource/h.maxResource*100)+'%';res.style.background=h.champion==='Zed'?'linear-gradient(90deg,#bd933e,#f3d57d)':'linear-gradient(90deg,#527ba8,#9bc6ed)';}
  put('moba-clock',String(Math.floor(s.time/60)).padStart(2,'0')+':'+String(Math.floor(s.time%60)).padStart(2,'0'));put('moba-kills',s.kills[0]+' : '+s.kills[1]);put('moba-blue-objective','我方塔 '+Math.round(s.towers[0].hp)+' · 主堡 '+Math.round(s.nexuses[0].hp));put('moba-red-objective','敵方塔 '+Math.round(s.towers[1].hp)+' · 主堡 '+Math.round(s.nexuses[1].hp));
  for(const b of document.querySelectorAll('[data-moba-skill]')){const i=Number(b.dataset.mobaSkill),cd=Math.max(0,h.cooldowns[i]-s.time);b.querySelector('b').textContent=d.skills[i];b.querySelector('small').textContent=d.cost[i]+(h.champion==='Zed'?' 能量':' 魔力');b.querySelector('.moba-cd').textContent=cd?cd.toFixed(1)+'s':'';b.setAttribute('aria-pressed',String(this.armed===i));b.disabled=!this.loaded||!this.supported||!s.running||s.paused||!h.hp||cd>0;b.title=d.tips[i];const icon=b.querySelector('.moba-skill-icon'),file=typeof leagueMeta!=='undefined'?leagueMeta[h.champion]?.spells?.[i]?.image?.full:null;if(icon){const url=file?'https://ddragon.leagueoflegends.com/cdn/16.19.1/img/spell/'+encodeURIComponent(file):'';icon.hidden=!url;if(url&&icon.getAttribute('src')!==url)icon.src=url;}}
  const start=document.querySelector('#moba-start');if(start){start.disabled=!this.loaded||!this.supported||s.running||s.winner!==null;put('moba-start',this.loaded?'開始對局':'正在載入戰場');}
  const pause=document.querySelector('#moba-pause');if(pause){pause.disabled=!s.running;put('moba-pause',s.paused?'繼續對局':'暫停');}
  for(const [id,at] of [['moba-flash',h.flashAt],['moba-heal',h.healAt]]){const b=document.querySelector('#'+id);if(b){b.disabled=!s.running||s.paused||!h.hp||at>s.time;b.querySelector('small').textContent=at>s.time?Math.ceil(at-s.time)+'s':'就緒';}}
  document.querySelectorAll('[data-moba-buy]').forEach(b=>b.disabled=!s.running||s.paused||!h.hp||h.items.length>=3||h.gold<Number(b.dataset.cost)||mobaDistance(h,s.nexuses[0])>170);put('moba-items',h.items.length?'已購買：'+h.items.map(i=>({sword:'長劍',health:'紅水晶',boots:'鞋子'}[i])).join('、'):'回到我方主堡附近購買，最多 3 件。');
  const tip=this.armed===null?this.quickCast?'QWER 朝游標快捷施法 · Shift＋QWER 預覽後點擊；右鍵移動、左鍵攻擊。':'QWER 選技能後點擊；右鍵移動、左鍵攻擊。':typeof this.armed==='number'?['Q','W','E','R'][this.armed]+' · '+d.tips[this.armed]+' 點擊施放，Esc 取消。':this.armed==='D'?'D · 點地面閃現，30 秒冷卻。':'A · 點地面攻擊移動。';put('moba-tip',tip);
  this.message(this.assetError||(!this.loaded?'正在載入戰場、建築與角色…':!h.hp?'你已倒下 · '+Math.ceil(h.respawnAt-s.time)+' 秒後復活':s.paused?'對局暫停，按「繼續對局」返回。':s.log));
 }
 draw(){const c=this.ctx,s=this.sim;if(!c)return;c.setTransform(this.ratio,0,0,this.ratio,0,0);c.clearRect(0,0,1280,720);this.map();
  for(const sh of s.shadows){const owner=s.find(sh.ownerId);this.sprite({...sh,type:'shadow',hp:1,pose:0,facing:owner?.facing||0},.38);c.save();c.strokeStyle='#aca2fc';c.lineWidth=2;c.beginPath();c.ellipse(sh.x,sh.y,30,13,0,0,Math.PI*2);c.stroke();c.restore();}
  const player=s.heroes[0],selected=s.find(player.targetId);if(player.hp){c.strokeStyle='#bdeddc';c.lineWidth=2;c.beginPath();c.ellipse(player.x,player.y,31,14,0,0,Math.PI*2);c.stroke();}if(selected?.hp){c.strokeStyle='#f29a94';c.lineWidth=2;c.beginPath();c.ellipse(selected.x,selected.y,selected.r+14,(selected.r+14)*.5,0,0,Math.PI*2);c.stroke();}
  for(const tower of s.towers)if(tower.hp&&tower.team===1&&mobaDistance(player,tower)<tower.range+75){c.strokeStyle='#e8968b70';c.lineWidth=2;c.setLineDash([7,7]);c.beginPath();c.arc(tower.x,tower.y,tower.range,0,Math.PI*2);c.stroke();c.setLineDash([]);}
  for(const u of [...s.units].sort((a,b)=>a.y-b.y)){if(['tower','nexus'].includes(u.type))this.structure(u);else if(u.type==='minion')this.minion(u);else this.sprite(u);if(u.hp)this.healthBar(u);}
  for(const p of s.projectiles)this.projectile(p);for(const f of s.fx)this.effect(f);
  for(const n of s.numbers){const t=(s.time-n.start)/.75;c.globalAlpha=1-t;c.font='bold 21px system-ui';c.textAlign='center';c.strokeStyle='#091019';c.lineWidth=4;c.strokeText(n.value,n.x,n.y-t*45);c.fillStyle='#ffe1af';c.fillText(n.value,n.x,n.y-t*45);c.globalAlpha=1;}
  this.aim();this.minimap();if(!s.running&&s.winner===null){c.fillStyle='#061421b8';c.fillRect(385,277,510,132);c.textAlign='center';c.fillStyle='#efdcaa';c.font='bold 27px system-ui';c.fillText('裂谷競技場',640,320);c.fillStyle='#c2d4e0';c.font='15px system-ui';c.fillText(s.practice?'練習假人 · 檢查命中、傷害與連招':'跟著小兵前進，擊破敵塔與主堡。',640,355);c.fillText('右鍵移動 · 左鍵攻擊 · Q W E R 施法',640,385);}
  if(s.paused&&s.running||s.winner!==null){c.fillStyle='#06121bd9';c.fillRect(380,282,520,112);c.fillStyle=s.winner===1?'#eeabab':'#f3d89e';c.font='bold 32px system-ui';c.textAlign='center';c.fillText(s.winner===null?'PAUSED · 暫停':s.winner===0?'VICTORY · 勝利':'DEFEAT · 落敗',640,328);c.font='14px system-ui';c.fillStyle='#c5d6e0';c.fillText(s.winner===null?'按繼續對局返回戰場':'這是本機對 AI 的對局；不產生天梯積分。',640,366);}
 }
 map(){const c=this.ctx;if(this.terrain?.complete&&this.terrain.naturalWidth){c.drawImage(this.terrain,0,0,1280,720);const shade=c.createRadialGradient(640,350,220,640,350,750);shade.addColorStop(0,'#07101500');shade.addColorStop(1,'#020b18a0');c.fillStyle=shade;c.fillRect(0,0,1280,720);for(let i=0;i<18;i++){const x=(i*193+73)%1280,y=(i*131+55)%720;if(y>200&&y<540)continue;const a=.18+.12*Math.sin(this.sim.time*.8+i);c.globalAlpha=a;c.fillStyle=i%3?'#a9eed0':'#afdfff';c.beginPath();c.arc(x+Math.sin(this.sim.time*.3+i)*9,y+Math.cos(this.sim.time*.4+i)*6,i%3?1.5:2.5,0,Math.PI*2);c.fill();}c.globalAlpha=1;return;}const g=c.createLinearGradient(0,0,1280,720);g.addColorStop(0,'#233c34');g.addColorStop(.55,'#172c2e');g.addColorStop(1,'#294231');c.fillStyle=g;c.fillRect(0,0,1280,720);
  for(let y=0;y<720;y+=30)for(let x=0;x<1280;x+=30){const n=((x*17+y*31)%97)/97;c.fillStyle='rgba(165,188,136,'+(n*.045)+')';c.fillRect(x+(n*9),y,16+n*12,2);}
  c.lineCap='round';c.strokeStyle='#081b2266';c.lineWidth=165;c.beginPath();c.moveTo(455,30);c.bezierCurveTo(575,175,600,390,825,735);c.stroke();c.strokeStyle='#23515c';c.lineWidth=110;c.stroke();c.strokeStyle='#47848a60';c.lineWidth=3;for(let i=0;i<12;i++){c.beginPath();c.moveTo(485+i*7,110);c.bezierCurveTo(550+i*5,270,650+i*3,450,770+i*6,670);c.stroke();}
  c.strokeStyle='#0b1726';c.lineWidth=146;c.beginPath();c.moveTo(100,600);c.bezierCurveTo(470,480,790,315,1180,120);c.stroke();c.strokeStyle='#777667';c.lineWidth=115;c.stroke();c.strokeStyle='#aaa18a66';c.lineWidth=95;c.stroke();
  for(let i=0;i<36;i++){const x=100+i*31,y=610-i*13.7;c.save();c.translate(x,y);c.rotate(-.42);c.strokeStyle='#424d4d';c.lineWidth=2;for(let j=-2;j<=2;j++){c.strokeRect(-15,j*19-9,27,16);}c.restore();}
  for(const rock of MOBA_ROCKS){c.fillStyle='#071b20aa';c.beginPath();c.ellipse(rock.x,rock.y+14,rock.r+13,rock.r*.58,0,0,Math.PI*2);c.fill();c.fillStyle='#3b4f50';c.beginPath();for(let i=0;i<7;i++){const a=i/7*Math.PI*2,r=rock.r*(i%2?.85:1);const x=rock.x+Math.cos(a)*r,y=rock.y+Math.sin(a)*r*.65-15;i?c.lineTo(x,y):c.moveTo(x,y);}c.closePath();c.fill();c.strokeStyle='#78918b';c.lineWidth=3;c.stroke();c.fillStyle='#496859';c.beginPath();c.ellipse(rock.x-12,rock.y-30,rock.r*.75,rock.r*.25,-.3,0,Math.PI*2);c.fill();}
  for(const [x,y] of [[190,160],[250,260],[165,350],[1080,450],[1100,570],[460,600],[805,120],[950,110]]){c.fillStyle='#0a252599';c.beginPath();c.ellipse(x,y+20,40,19,0,0,Math.PI*2);c.fill();for(let k=0;k<3;k++){c.fillStyle=['#244a3b','#376750','#548665'][k];c.beginPath();c.moveTo(x-36+k*7,y+15-k*20);c.lineTo(x,y-70-k*4);c.lineTo(x+36-k*7,y+15-k*20);c.closePath();c.fill();}}
  c.strokeStyle='#8aafa933';c.lineWidth=2;c.strokeRect(35,70,1210,590);c.font='11px system-ui';c.fillStyle='#b2cbb5aa';c.textAlign='left';c.fillText('SINGLE LANE / LOCAL AI MATCH',52,48);
 }
 sprite(u,opacity=1){if(!this.loaded)return;const c=this.ctx,t=this.sim.time,hound=u.champion==='Naafiri',small=u.type==='hound',dir=mobaDirection(u.facing),moving=u.pose===1,action=[3,4,5].includes(u.pose),row=(hound?4:0)+(moving?1+Math.floor(t*9)%2:action?3:0),w=small?72:hound?158:150,h=w;
  c.save();c.globalAlpha=opacity*(u.invulnerableUntil>t?.4:1);c.fillStyle='#020b16aa';c.beginPath();c.ellipse(u.x,u.y,small?16:28,small?7:12,0,0,Math.PI*2);c.fill();c.translate(u.x,u.y);
  if(!u.hp){const back=Math.sin(u.facing)<-.1,mirror=back?Math.cos(u.facing)>0:Math.cos(u.facing)<0;if(mirror)c.scale(-1,1);c.drawImage(this.atlas,7*192,((hound?2:0)+(back?1:0))*256,192,256,-w/2,-h*.88,w,h);}
  else{const bob=moving?Math.sin(t*18)*1.5:Math.sin(t*2+u.id)*.6,recoil=u.pose===6?Math.sin((u.poseUntil-t)*25)*3:0;c.translate(recoil,bob);const phase=mobaClamp((u.poseUntil-t)/.25,0,1);if(action){c.translate(Math.cos(u.facing)*3*(1-phase),Math.sin(u.facing)*2*(1-phase));c.scale(1+(u.pose===4?.04:-.015)*phase,1-(u.pose===4?.025:0)*phase);}const cw=this.directions.naturalWidth/8,ch=this.directions.naturalHeight/8;c.drawImage(this.directions,dir*cw,row*ch,cw,ch,-w/2,-h*.89,w,h);}
  c.restore();if(u.type==='hero'&&u.shield>0){c.strokeStyle='#b0defa';c.lineWidth=2;c.beginPath();c.ellipse(u.x,u.y-46,42,61,0,0,Math.PI*2);c.stroke();}
 }
 worldObject(column,team,x,y,width,height,alpha=1){if(!this.props?.naturalWidth)return;const c=this.ctx,scaleX=this.props.naturalWidth/1536,scaleY=this.props.naturalHeight/1024,bounds=[[0,370],[385,855],[860,1230],[1235,1536]][column];const row=team===0?{y:0,h:column===0?490:500,anchor:column===0?.99:column===1?.98:.95}:{y:column===0?490:512,h:column===0?534:512,anchor:column<2?.92:.88};c.save();c.globalAlpha=alpha;c.drawImage(this.props,bounds[0]*scaleX,row.y*scaleY,(bounds[1]-bounds[0])*scaleX,row.h*scaleY,x-width/2,y-height*row.anchor,width,height);c.restore();}
 minion(u){const c=this.ctx,w=u.ranged?43:46,h=58,bob=u.pose===1?Math.sin(this.sim.time*12+u.id)*1.6:0;c.fillStyle='#030c18a0';c.beginPath();c.ellipse(u.x,u.y,14,6,0,0,Math.PI*2);c.fill();this.worldObject(u.ranged?3:2,u.team,u.x,u.y+bob,w,h);if(u.pose===4){c.strokeStyle=u.team?'#faab9477':'#91e9ff77';c.lineWidth=2;c.beginPath();c.arc(u.x,u.y-22,20,this.sim.time*8,this.sim.time*8+2);c.stroke();}}
 structure(u){const c=this.ctx,color=u.team?'#f96e7b':'#69d8ff',nexus=u.type==='nexus';c.save();c.translate(u.x,u.y);c.fillStyle='#02081390';c.beginPath();c.ellipse(0,0,nexus?45:40,nexus?17:14,0,0,Math.PI*2);c.fill();if(u.hp){const glow=c.createRadialGradient(0,-30,2,0,-30,nexus?70:62);glow.addColorStop(0,u.team?'#ef6a7020':'#63d9ff20');glow.addColorStop(1,'#00000000');c.fillStyle=glow;c.fillRect(-80,-120,160,140);}else{for(let i=0;i<7;i++){c.save();c.translate(Math.sin(i*2.3)*33,Math.cos(i*2.3)*10-5);c.rotate(i*1.7);c.fillStyle=i%2?'#596259':'#3d4942';c.strokeStyle='#17261f';c.lineWidth=2;c.fillRect(-8,-6,19,12);c.strokeRect(-8,-6,19,12);c.restore();}c.restore();return;}c.restore();this.worldObject(nexus?1:0,u.team,u.x,u.y,nexus?120:125,nexus?126:174);}

 healthBar(u){const c=this.ctx,w=u.type==='hero'?92:u.type==='tower'||u.type==='nexus'?94:39,y=u.y-(u.type==='hero'?130:u.type==='tower'?176:u.type==='nexus'?122:u.type==='hound'?61:60);const barY=Math.max(8,y);c.fillStyle='#040b13';c.fillRect(u.x-w/2-1,barY-1,w+2,7);c.fillStyle=u.team?'#e77e84':'#76dbbe';c.fillRect(u.x-w/2,barY,w*u.hp/u.maxHP,5);if(u.type==='hero'){c.font='bold 11px system-ui';c.textAlign='center';c.fillStyle='#eee8d7';c.fillText(u.dummy?'練習假人':MOBA_HEROES[u.champion].name+' · '+u.level,u.x,y-6);}}
 projectile(p){const c=this.ctx,angle=Math.atan2(p.vy,p.vx);c.save();c.translate(p.x,p.y-10);c.rotate(angle);c.shadowColor=p.team?'#ef9999':'#8cdbf0';c.shadowBlur=14;c.fillStyle=p.team?'#f4a0a5':'#a1e6f8';if(p.type==='shuriken'){c.rotate(this.sim.time*19);c.beginPath();for(let i=0;i<8;i++){const r=i%2?5:17,a=i*Math.PI/4;i?c.lineTo(Math.cos(a)*r,Math.sin(a)*r):c.moveTo(Math.cos(a)*r,Math.sin(a)*r);}c.closePath();c.fill();}else if(p.type==='dagger'){c.fillStyle='#f2bec0';c.beginPath();c.moveTo(23,0);c.lineTo(-12,-6);c.lineTo(-4,0);c.lineTo(-12,6);c.closePath();c.fill();}else{c.beginPath();c.arc(0,0,p.type==='tower'?11:5,0,Math.PI*2);c.fill();}c.restore();}
 effect(f){const c=this.ctx,t=(this.sim.time-f.start)/(f.end-f.start),target=f.targetId?this.sim.find(f.targetId):null,x=target?.x||f.x,y=target?.y||f.y,color=f.team?'#ee979b':'#9bdbef';c.save();c.globalAlpha=1-t;c.strokeStyle=['heal','recall'].includes(f.type)?'#8ee6ae':f.type==='mark'?'#f392ac':color;c.fillStyle=c.strokeStyle;c.lineWidth=3;
  if(f.type==='dash'||f.type==='flash'){c.lineWidth=22*(1-t);c.beginPath();c.moveTo(f.from.x,f.from.y-12);c.lineTo(x,y-12);c.stroke();}
  else if(f.type==='slash'){c.lineWidth=5;c.beginPath();c.ellipse(x,y-25,(f.radius||50)*(t*.5+.5),(f.radius||50)*.45,0,Math.PI*t*2,Math.PI*t*2+4);c.stroke();}
  else if(f.type==='mark'||f.type==='target'){c.beginPath();c.arc(x,y-65,30+Math.sin(t*20)*4,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(x-17,y-82);c.lineTo(x+17,y-48);c.moveTo(x+17,y-82);c.lineTo(x-17,y-48);c.stroke();}
  else if(f.type==='move'){c.beginPath();c.ellipse(x,y,8+25*t,4+12*t,0,0,Math.PI*2);c.stroke();}
  else{c.beginPath();c.ellipse(x,y-15,15+t*(f.type==='howl'?130:55),9+t*25,0,0,Math.PI*2);c.stroke();if(f.type==='level'||f.type==='heal'){c.beginPath();c.moveTo(x,y-10);c.lineTo(x,y-100*t);c.stroke();}}
  c.restore();}
 aim(){if(this.armed===null)return;const c=this.ctx,h=this.sim.heroes[0],target=this.hitTest(this.mouse),p=target||this.mouse,i=this.armed,range=i==='D'?210:i===1?330:i===2?(h.champion==='Zed'?130:260):i===3?540:640;const d=mobaDistance(h,p),k=Math.min(1,range/(d||1)),end={x:h.x+(p.x-h.x)*k,y:h.y+(p.y-h.y)*k};c.save();c.strokeStyle='#9be3dbaa';c.fillStyle='#8eddcd10';c.lineWidth=2;c.setLineDash([6,5]);c.beginPath();c.arc(h.x,h.y,range,0,Math.PI*2);c.fill();c.stroke();c.setLineDash([]);if(i===2&&h.champion==='Zed'){c.beginPath();c.ellipse(h.x,h.y,130,65,0,0,Math.PI*2);c.stroke();}else{c.lineWidth=i===0?18:4;c.strokeStyle='#b3f1e75a';c.beginPath();c.moveTo(h.x,h.y);c.lineTo(end.x,end.y);c.stroke();c.lineWidth=2;c.strokeStyle=i===3&&!target?'#f19e9e':'#e0f7e9';c.beginPath();c.arc(end.x,end.y,15,0,Math.PI*2);c.stroke();}c.restore();}
 minimap(){const c=this.ctx,x=1078,y=565,w=168,h=100;c.fillStyle='#04131ccd';c.fillRect(x-3,y-3,w+6,h+6);if(this.terrain?.naturalWidth)c.drawImage(this.terrain,x,y,w,h);c.fillStyle='#04131c44';c.fillRect(x,y,w,h);c.strokeStyle='#b9a774aa';c.lineWidth=1.5;c.strokeRect(x,y,w,h);for(const u of this.sim.units)if(u.hp){c.fillStyle=u.team?'#f29396':'#8bdfec';const xx=x+u.x/1280*w,yy=y+u.y/720*h;c.beginPath();c.arc(xx,yy,u.type==='hero'?4:2,0,Math.PI*2);c.fill();}c.font='9px system-ui';c.fillStyle='#c4d0c7';c.textAlign='left';c.fillText('戰場概覽',x+5,y-6);}
}
function initLeagueStage(){
 const root=document.createElement('section');root.className='moba-arena';root.id='moba-arena';root.setAttribute('aria-label','可操作英雄競技場');root.innerHTML=`
 <div class="moba-head"><div><span class="moba-kicker">CHAMPION ARENA · PLAYABLE MOBA</span><h2>裂谷競技場</h2><p>走位、影分身、犬群與推塔。每次命中都由實際位置決定。</p></div><div class="moba-actions"><button id="moba-start" class="moba-primary">開始對局</button><button id="moba-pause" disabled>暫停</button><button id="moba-reset">新對局</button><button id="moba-fullscreen" aria-pressed="false">放大戰場</button></div></div>
 <div class="moba-toolbar"><label>戰鬥英雄<select id="moba-champion"><option value="Zed">劫 · 影分身刺客</option><option value="Naafiri">娜菲芮 · 犬群刺客</option></select></label><label>模式<select id="moba-mode"><option value="match">對戰 AI</option><option value="practice">練習假人</option></select></label><label class="moba-auto"><input id="moba-quick" type="checkbox" checked> 快捷施法</label><span class="moba-note" id="moba-roster-note"></span><label class="moba-auto"><input type="checkbox" id="moba-auto"> 自動示範（AI 接管我方）</label></div>
 <div id="moba-training" class="moba-training" hidden><div><b>連招練習</b><span id="moba-training-stats">累積傷害 0 · 命中 0 · DPS 0</span><small>假人不反擊，無小兵與塔攻擊。DPS 從首次命中算起，包含等待時間。</small></div><label><input id="moba-unlimited" type="checkbox"> 無冷卻／無限資源</label><button id="moba-training-reset">重置假人與技能</button></div>
 <div class="moba-scoreboard"><div class="blue">我方陣營<small id="moba-blue-objective"></small></div><div class="score-center"><span id="moba-kills">0 : 0</span><small id="moba-clock">00:00</small></div><div class="red">敵方陣營<small id="moba-red-objective"></small></div></div>
 <div class="moba-viewport"><canvas id="battle-canvas" tabindex="0" aria-label="劫與娜菲芮的可操作俯視角戰場"></canvas><div id="moba-gate" class="moba-gate" hidden><b>此英雄尚未製作可玩動作</b><p>目前戰鬥版支援劫與娜菲芮。選擇下方英雄即可進入戰場；其他英雄仍可在收藏中查看。</p><div><button data-moba-choose="Zed">使用劫</button><button data-moba-choose="Naafiri">使用娜菲芮</button></div></div></div>
 <div class="moba-hud"><div class="moba-player"><img id="moba-portrait" class="moba-portrait" alt="戰鬥英雄"><h3 id="moba-player"></h3><div class="moba-stats" id="moba-stats" style="white-space:pre-line"></div><div class="moba-meter" aria-label="英雄生命"><i id="moba-hp"></i></div><div class="moba-meter resource" aria-label="英雄能量或魔力"><i id="moba-resource"></i></div></div><div class="moba-skill-grid">${[0,1,2,3].map(i=>'<button class="moba-skill" type="button" data-moba-skill="'+i+'" aria-pressed="false"><img class="moba-skill-icon" alt="" hidden><kbd>'+['Q','W','E','R'][i]+'</kbd><b></b><small></small><span class="moba-cd"></span></button>').join('')}</div><div class="moba-summoners"><button id="moba-flash"><kbd>D</kbd>閃現<small>就緒</small></button><button id="moba-heal"><kbd>F</kbd>治療<small>就緒</small></button><button id="moba-recall"><kbd>B</kbd>回城<small>3 秒</small></button></div></div>
 <p id="moba-tip" class="moba-tip"></p><p id="duel-status" class="moba-help" role="status" aria-live="polite"></p><p class="moba-help"><kbd>右鍵</kbd> 移動 · <kbd>左鍵</kbd> 攻擊敵軍 · <kbd>Q W E R</kbd> 朝游標快捷施法 · <kbd>Shift＋技能</kbd> 瞄準預覽 · <kbd>A</kbd> 攻擊移動 · <kbd>S</kbd> 停止 · <kbd>Esc</kbd> 取消 · <kbd>空白鍵</kbd> 暫停。手機：點地面移動、點敵軍攻擊，先點技能再點戰場施放。</p>
 <div class="moba-shop"><span>基地商店</span><button data-moba-buy="sword" data-cost="350">長劍 · 350 G / +20 攻擊</button><button data-moba-buy="health" data-cost="400">紅水晶 · 400 G / +180 HP</button><button data-moba-buy="boots" data-cost="300">鞋子 · 300 G / +35 移速</button><small id="moba-items"></small></div>
 <p class="moba-note">單人對 AI 的非官方 MOBA 原型：獨立實作傷害、碰撞、命中、塔仇恨、小兵、補刀、金幣、對局升級、商店與死亡復活。動作素材為重新繪製的經典角色；其他收藏造型尚無戰鬥動作。數值、地圖與平衡為本專案設定，並非原版 LOL 引擎。對局金幣與經驗只在本局使用，不影響學習、個人、陣營或公會天梯。</p>`;
 document.querySelector('.hero-main').append(root);mobaRenderer=new MobaCanvas(document.querySelector('#battle-canvas'));
 const choose=champion=>{leagueSave({champion,skin:0,auto:false});fetchLeagueMeta();};document.querySelector('#moba-champion').onchange=e=>choose(e.target.value);document.querySelectorAll('[data-moba-choose]').forEach(b=>b.onclick=()=>choose(b.dataset.mobaChoose));
 document.querySelector('#moba-start').onclick=()=>{mobaRenderer.sim.start();mobaRenderer.canvas.focus();mobaRenderer.updateUI(true);};document.querySelector('#moba-reset').onclick=()=>{mobaRenderer.sim.reset(mobaRenderer.sim.heroes[0].champion);mobaRenderer.armed=null;document.querySelector('#moba-auto').checked=false;mobaRenderer.updateUI(true);};document.querySelector('#moba-pause').onclick=()=>{mobaRenderer.sim.paused=!mobaRenderer.sim.paused;mobaRenderer.updateUI(true);};document.querySelector('#moba-auto').onchange=e=>mobaRenderer.sim.auto=e.target.checked;document.querySelector('#moba-quick').onchange=e=>mobaRenderer.quickCast=e.target.checked;document.querySelector('#moba-mode').onchange=e=>{mobaRenderer.sim.reset(mobaRenderer.sim.heroes[0].champion,e.target.value==='practice');mobaRenderer.armed=null;document.querySelector('#moba-auto').checked=false;mobaRenderer.updateUI(true);};document.querySelector('#moba-unlimited').onchange=e=>mobaRenderer.sim.unlimited=e.target.checked;document.querySelector('#moba-training-reset').onclick=()=>{mobaRenderer.sim.refreshPractice();mobaRenderer.armed=null;mobaRenderer.updateUI(true);};document.querySelector('#moba-fullscreen').onclick=()=>{const expanded=root.classList.toggle('moba-expanded');document.body.classList.toggle('moba-focused',expanded);root.scrollTop=0;const button=document.querySelector('#moba-fullscreen');button.textContent=expanded?'返回頁面':'放大戰場';button.setAttribute('aria-pressed',String(expanded));mobaRenderer.resize();};
 document.querySelectorAll('[data-moba-skill]').forEach(b=>b.onclick=()=>{mobaRenderer.arm(Number(b.dataset.mobaSkill));mobaRenderer.canvas.focus();});document.querySelector('#moba-flash').onclick=()=>{mobaRenderer.arm('D');mobaRenderer.canvas.focus();};document.querySelector('#moba-heal').onclick=()=>mobaRenderer.sim.heal();document.querySelector('#moba-recall').onclick=()=>mobaRenderer.sim.recall();document.querySelectorAll('[data-moba-buy]').forEach(b=>b.onclick=()=>{mobaRenderer.sim.buy(b.dataset.mobaBuy);mobaRenderer.updateUI(true);});
}
function renderLeagueStage(){if(!mobaRenderer)return;const selected=leagueSelected(),id=selected.champion.id,supported=Boolean(MOBA_HEROES[id]),wasSupported=mobaRenderer.supported;mobaRenderer.supported=supported;document.querySelector('#moba-gate').hidden=supported;
 if(supported&&(!wasSupported||mobaRenderer.sim.heroes[0].champion!==id)){mobaRenderer.sim.reset(id);mobaRenderer.armed=null;document.querySelector('#moba-auto').checked=false;}
 if(!supported)mobaRenderer.sim.paused=true;document.querySelector('#moba-champion').value=supported?id:'';document.querySelector('#moba-roster-note').textContent=supported?'八方向經典模型 · '+MOBA_HEROES[id].name:'收藏英雄 '+selected.champion.name+' 暫無戰鬥模型';document.querySelector('#battle-canvas').setAttribute('aria-label',supported?MOBA_HEROES[id].name+' 的可操作 MOBA 戰場；右鍵移動、QWER 瞄準':'尚未提供 '+selected.champion.name+' 的戰鬥模型');mobaRenderer.updateUI(true);
}
function animateLeagueDuel(index){if(!mobaRenderer)return false;mobaRenderer.arm(index);mobaRenderer.canvas.focus();return false;}
function cancelLeagueDuel(){if(mobaRenderer)mobaRenderer.sim.paused=true;}
