const vm=require('vm'),fs=require('fs'),assert=require('assert');
const src=fs.readFileSync('site/moba.js','utf8'),ctx=vm.createContext({});vm.runInContext(src+';this.Sim=MobaSimulation;this.path=mobaPath;this.walkable=mobaWalkable;',ctx);const Sim=ctx.Sim;let n=0;const check=(v,m)=>{assert(v,m);n++;};
function run(s,t){for(let i=0;i<Math.ceil(t/.025);i++)s.step(.025);}
function setup(champion='Zed'){const s=new Sim(champion);s.start();s.nextWave=999;s.heroes[1].aiAt=999;for(const u of s.units.filter(u=>u.type==='hound'))u.hp=0;s.heroes[0].x=480;s.heroes[0].y=360;s.heroes[1].x=700;s.heroes[1].y=360;return s;}
let s=setup();check(s.heroes[0].champion==='Zed'&&s.heroes[1].champion==='Naafiri','correct bodies');let hp=s.heroes[1].hp;check(s.cast(0,{x:1000,y:360}),'Q cast');run(s,.7);check(s.heroes[1].hp<hp,'Q real collision');check(!s.cast(0,{x:1000,y:360}),'Q cooldown');
s=setup();hp=s.heroes[1].hp;s.cast(0,{x:1000,y:510});run(s,1);check(s.heroes[1].hp>=hp,'misses do not damage');
s=setup();s.heroes[0].resource=1;check(!s.cast(0,s.heroes[1]),'resource guard');check(s.heroes[1].hp===hp,'guard does not damage');
s=setup();check(s.cast(1,{x:600,y:360}),'shadow placement');run(s,.4);check(s.shadows.length===1,'shadow exists');check(s.cast(1,{x:300,y:350}),'shadow swap');check(Math.abs(s.heroes[0].x-600)<1,'swap moves real body');check(s.heroes[0].cooldowns[1]>s.time+5,'swap does not reset cooldown');
s=setup();s.cast(1,{x:600,y:360});run(s,5.1);check(s.shadows.length===0,'shadow expiry');check(!s.cast(1,{x:650,y:360}),'expired shadow respects original cooldown');
s=setup();s.heroes[1].x=575;s.cast(1,{x:570,y:400});run(s,.3);hp=s.heroes[1].hp;s.cast(2,s.heroes[1]);check(s.heroes[1].hp<hp&&s.heroes[1].slowUntil>s.time,'E AoE and slow');
s=setup();check(!s.cast(3,{x:10,y:10}),'R must target hero');check(s.cast(3,s.heroes[1]),'R valid target');run(s,.5);check(s.marks.length===1,'death mark created');s.heroes[0].targetId=null;s.heroes[1].targetId=null;s.heroes[1].aiAt=999;const target=s.heroes[1];s.damage(target,100,s.heroes[0]);check(s.marks[0].stored>=100,'death mark stores damage');hp=target.hp;run(s,3.1);check(target.hp<hp-100,'mark explosion adds damage');
s=setup('Naafiri');hp=s.heroes[1].hp;check(s.cast(0,s.heroes[1]),'dagger cast');run(s,.5);check(s.bleeds.length===1,'dagger bleed');check(s.cast(0,s.heroes[1]),'dagger recast');run(s,.6);check(s.heroes[1].hp<hp-220,'second dagger amplifies');
s=setup('Naafiri');s.cast(0,{x:1000,y:550});run(s,3.2);check(!s.cast(0,s.heroes[1]),'unused recast preserves cooldown');
s=setup('Naafiri');check(s.cast(1,s.heroes[0]),'pack W');check(s.units.filter(u=>u.type==='hound'&&u.hp).length===3,'additional hounds');hp=s.heroes[0].hp;s.damage(s.heroes[0],100,s.heroes[1]);check(s.heroes[0].hp===hp,'W untargetability');run(s,.8);s.damage(s.heroes[0],100,s.heroes[1]);check(s.heroes[0].hp<hp,'untargetability expires');
s=setup('Naafiri');const oldX=s.heroes[0].x;check(s.cast(2,{x:650,y:360}),'hound dash');check(s.heroes[0].x>oldX+100,'dash moves body');
s=setup('Naafiri');check(s.cast(3,s.heroes[1]),'pursuit cast');run(s,.6);check(s.heroes[0].x>600&&s.heroes[1].hp<s.heroes[1].maxHP,'pursuit moves and damages');s.damage(s.heroes[1],9999,s.heroes[0]);check(s.heroes[0].pursuitRecast,'pursuit kill recast');
s=setup();const nexus=s.nexuses[1];hp=nexus.hp;s.damage(nexus,500,s.heroes[0]);check(nexus.hp===hp,'tower protects nexus');s.damage(s.towers[1],9999,s.heroes[0]);s.damage(nexus,9999,s.heroes[0]);check(s.winner===0&&!s.running,'nexus victory');
s=setup();s.damage(s.heroes[0],9999,s.heroes[1]);check(s.heroes[0].hp===0&&!s.cast(0,s.heroes[1]),'death locks skills');run(s,7.1);check(s.heroes[0].hp>0&&s.kills[1]===1,'respawn and kill count');
s=setup();s.paused=true;run(s,2);check(s.time===0,'pause freezes simulation');s.paused=false;run(s,.1);check(s.time>0,'resume');
s=setup();check(s.command({x:780,y:170}),'movement command');const path=ctx.path({x:280,y:205},{x:500,y:205});check(path.length>1&&path.every(p=>ctx.walkable(p)),'path routes around rocks');check(ctx.path({x:280,y:205},{x:385,y:205}).length===0,'blocked target rejected');
s=setup();const tower=s.towers[1];s.heroes[0].x=900;s.heroes[0].y=300;const min=s.unit('minion',0,905,300,300);s.units.push(min);run(s,.1);check(tower.targetId===min.id,'tower prioritizes wave');s.damage(s.heroes[1],1,s.heroes[0]);check(tower.targetId===s.heroes[0].id,'tower retaliates champion damage');
s=setup();const min2=s.unit('minion',1,650,350,50);s.units.push(min2);const gold=s.heroes[0].gold;s.damage(min2,100,s.heroes[0]);check(s.heroes[0].cs===1&&s.heroes[0].gold>=gold+25,'last hit gives gold');s.heroes[0].gold=400;check(!s.buy('sword'),'shop requires base');s.heroes[0].x=140;s.heroes[0].y=560;check(s.buy('sword')&&s.heroes[0].items.length===1,'base purchase');
s=setup();s.heroes[0].hp=500;s.recall();run(s,1);s.damage(s.heroes[0],1,s.heroes[1]);check(s.heroes[0].recallAt===0,'damage cancels recall');check(s.flash({x:600,y:390}),'flash');check(!s.flash({x:650,y:400}),'flash cooldown');
for(const hero of ['Zed','Naafiri']){s=new Sim(hero);s.start();s.auto=true;run(s,180);check(s.units.length<80,'bounded units');check(s.units.every(u=>Number.isFinite(u.hp)&&u.hp>=0&&Number.isFinite(u.x)&&Number.isFinite(u.y)),'long match finite state');check(s.heroes.every(h=>h.resource>=0&&h.resource<=h.maxResource),'resources bounded');check(s.wave>5,'minion waves advance');}
for(const hero of ['Zed','Naafiri']){s=new Sim(hero);s.start();s.auto=true;run(s,480);check(s.winner!==null&&s.nexuses.some(n=>n.hp===0),'complete AI match reaches nexus victory');}
check(!/localStorage|competitionCall|saveQuizState|\.rpc\(/.test(src),'no persistence or competition writes');
console.log(n+' checks passed: real skill hits/misses, resources, cooldowns, shadows, marks, hounds, dashes, tower aggro, nexus shields, death/respawn, pathfinding, waves, last hits, shop, pause, long AI matches and score separation.');
