const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const storage=new Map(),nodes=new Map();
const node=key=>{if(!nodes.has(key))nodes.set(key,{value:key==='#quiz-category'||key==='#quiz-type'?'all':'',innerHTML:'',textContent:'',className:'',dataset:{},classList:{toggle(){},add(){},remove(){}},appendChild(){},insertAdjacentHTML(){},querySelectorAll(){return [];},querySelector(k){return node(k);},focus(){},setAttribute(){}});return nodes.get(key);};
const context=vm.createContext({console,window:{},Date,Math,document:{querySelector:node,querySelectorAll:()=>[],createElement:()=>node(Math.random().toString()),head:{appendChild(){}}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},openOnlyModule(){},confirm:()=>true});
vm.runInContext(fs.readFileSync(__dirname+'/data.js','utf8'),context);
vm.runInContext('const d=window.CLOUD_SA_DATA;',context);
const app=fs.readFileSync(__dirname+'/app.js','utf8'),a=app.indexOf('// Mixed practice'),b=app.indexOf("const root=document.querySelector('#days');",a);
vm.runInContext(fs.readFileSync(__dirname+'/drag-quiz.js','utf8'),context);
vm.runInContext(app.slice(a,b),context);
const run=s=>vm.runInContext(s,context);
assert.equal(run('extendedQuizBank.length'),14);
assert.equal(run('new Set(quizBank.map(q=>q.id)).size===quizBank.length'),true);
run(`for(const q of extendedQuizBank){if(q.type==='short'){if(!q.rubric.length)throw Error('Missing rubric');continue;}const answer=q.type==='combo'?q.fields.map(f=>f.answer):q.answer;if(!gradeObjective(q,answer))throw Error(q.id+' correct failed');const wrong=[...answer];wrong[0]=(wrong[0]+1)%3;if(gradeObjective(q,wrong))throw Error(q.id+' wrong passed');}`);
run(`localStorage.setItem(quizStateKey,JSON.stringify({attempts:10,correct:7,missed:{"MIX-M01":2}}));recordQuizResult(extendedQuizBank[0],true);`);
assert.equal(run('quizState().attempts'),11);assert.equal(run('quizState().correct'),8);assert.equal(run('Boolean(quizState().missed["MIX-M01"])'),true);
run('recordQuizResult(extendedQuizBank[0],true)');assert.equal(run('quizState().reviews["MIX-M01"].streak'),1);
assert.equal(run('quizState().reviews["MIX-M01"].stage'),1);
run(`const s=quizState();s.reviews["MIX-M01"].lastSuccess='2000-01-01';s.reviews["MIX-M01"].due=localDay();saveQuizState(s);recordQuizResult(extendedQuizBank[0],true);`);
assert.equal(run('Boolean(quizState().missed["MIX-M01"])'),false);assert.equal(run('quizState().reviews["MIX-M01"].stage'),2);
run(`recordQuizResult(extendedQuizBank[0],false)`);assert.equal(run('quizState().reviews["MIX-M01"].stage'),0);assert.equal(run('quizState().reviews["MIX-M01"].streak'),0);
const attempts=run('quizState().attempts');run('recordQuizResult(extendedQuizBank.find(q=>q.id==="MIX-S01"),false,true)');assert.equal(run('quizState().attempts'),attempts);assert.equal(run('quizState().selfAttempts'),1);
assert.equal(run('dueQuestion(extendedQuizBank[0],quizState())'),false);
run(`const t=quizState();t.reviews["MIX-M01"].due=localDay();saveQuizState(t);`);assert.equal(run('dueQuestion(extendedQuizBank[0],quizState())'),true);
// Exercise rendering each type, with a minimal document stub.
for(const type of ['single','multi','combo','order','match']){node('#quiz-type').value=type;run('currentQuestion=null;nextQuizQuestion()');assert.ok(node('#quiz-options').innerHTML.length);}
node('#quiz-type').value='all';run('setQuizMode("due")');assert.ok(node('#quiz-question').textContent.length);
assert.equal(run('escapeQuiz("<script>hello</script>")'),'&lt;script&gt;hello&lt;/script&gt;');
run(`localStorage.setItem(quizStateKey,'invalid JSON');`);assert.equal(run('quizState().attempts'),0);
console.log('PASS: 14 new questions; correct / wrong scoring; original state migration; distinct-day scheduling; missed retention; self-assessment separated from objective accuracy; due filtering; all five render paths; output escaping; invalid storage recovery. Total bank: '+run('quizBank.length'));
context.document.querySelector=()=>null;
vm.runInContext(fs.readFileSync(__dirname+'/game-ui.js','utf8').replace(/initGameUI\(\);\s*$/,''),context);
run(`localStorage.removeItem(quizStateKey);recordQuizResult(extendedQuizBank[0],false);`);
assert.equal(run('quizState().game.xp'),5);
run('recordQuizResult(extendedQuizBank[0],true)');assert.equal(run('quizState().game.xp'),20);
run('recordQuizResult(extendedQuizBank[0],true)');assert.equal(run('quizState().game.xp'),20);
assert.equal(run('gameDay(quizState()).objective.length'),1);
run(`recordQuizResult(extendedQuizBank.find(q=>q.id==='MIX-S01'),true,true);`);
assert.equal(run('quizState().game.xp'),35);assert.equal(run('gameDay(quizState()).short.length'),1);
assert.equal(run('gameStreak(gameState(quizState()))'),1);
assert.equal(run('gameLevel(200).level'),2);assert.equal(run('gameLevel(235).progress'),35);
assert.ok(run('scoreChart(d.scores).includes("Day 12：88 分")'));
assert.equal(run('quizState().attempts'),3);assert.equal(run('quizState().selfAttempts'),1);
console.log('PASS: XP capped per question / day, partial reward upgrade, unique daily mission counts, separate short assessment, level progression, daily streak and historical score values.');

vm.runInContext(fs.readFileSync(__dirname+'/blue-ui.js','utf8').replace(/initFantasyGame\(\);\s*$/,''),context);
assert.equal(run("availableRole(2,'paladin').id"),'mage');
assert.equal(run("availableRole(3,'paladin').id"),'paladin');
assert.equal(run("availableRole(4,'ranger').id"),'mage');
assert.equal(run("availableRole(5,'ranger').id"),'ranger');
assert.equal(run("fantasyTitle(availableRole(5,'paladin'),5).name"),'守護聖騎士');
assert.equal(run("fantasyTitle(availableRole(10,'mage'),10).name"),'星辰大法師');
assert.equal(run('worldNodes.length'),run('d.skillMap.domains.length'));
assert.equal(run('worldNodes.every(n=>n.x>0&&n.x<960&&n.y>0&&n.y<600)'),true);
console.log('PASS: profession unlock boundaries, earned titles, and all map regions.');

vm.runInContext(fs.readFileSync(__dirname+'/arena.js','utf8').replace(/initArena\(\);\s*$/,''),context);
run("const cg={xp:200,days:{},rewarded:{}};");
run("trackCorrectChain(cg,{id:'a'},true,false,'2026-10-01');trackCorrectChain(cg,{id:'a'},true,false,'2026-10-01')");
assert.equal(run('cg.chain'),1);
run("trackCorrectChain(cg,{id:'b'},true,false,'2026-10-01');trackCorrectChain(cg,{id:'c'},true,false,'2026-10-01')");
assert.equal(run('cg.chain'),3);assert.equal(run("cg.weapons.includes('mist')"),true);
assert.equal(run("currentWeapon(cg).id"),'mist');
run("trackCorrectChain(cg,{id:'s'},false,true,'2026-10-01')");assert.equal(run('cg.chain'),3);
run("trackCorrectChain(cg,{id:'a'},false,false,'2026-10-01')");assert.equal(run('cg.chain'),0);assert.equal(run('cg.bestChain'),3);assert.equal(run('cg.weapons.length'),1);
run("trackCorrectChain(cg,{id:'a'},true,false,'2026-10-01')");assert.equal(run('cg.chain'),0);
run("trackCorrectChain(cg,{id:'a'},true,false,'2026-10-02')");assert.equal(run('cg.chain'),1);
run("for(let i=0;i<19;i++)trackCorrectChain(cg,{id:'new'+i},true,false,'2026-10-02')");assert.equal(run('cg.chain'),20);assert.equal(run('cg.bestChain'),20);assert.equal(run('cg.weapons.length'),4);
run("trackCorrectChain(cg,{id:'another'},true,false,'2026-10-03')");assert.equal(run('cg.chain'),21);assert.equal(run('cg.weapons.length'),4);
run("localStorage.removeItem(quizStateKey);recordQuizResult(extendedQuizBank[0],true)");assert.equal(run('quizState().game.chain'),1);assert.equal(run('quizState().game.xp'),20);
run("recordQuizResult(extendedQuizBank[0],true)");assert.equal(run('quizState().game.chain'),1);
run("recordQuizResult(extendedQuizBank[0],false)");assert.equal(run('quizState().game.chain'),0);
assert.equal(run('rankingConfigured()'),false);
run("window.CLOUD_RANKING_CONFIG={url:'https://project.supabase.co',publishableKey:'sb_publishable_test'}");assert.equal(run('rankingConfigured()'),true);
run("window.CLOUD_RANKING_CONFIG.publishableKey='sb_secret_invalid'");assert.equal(run('rankingConfigured()'),false);
assert.ok(run("weaponArt('paladin',weaponTiers[0]).includes('晨霧長劍')"));
console.log('PASS: unique-question correct chains, wrong reset, self-assessment excluded, cross-day persistence, all weapon thresholds and retention, reward integration, offline leaderboard and public-key-only config.');

assert.equal(run("quizBank.some(q=>q.type==='short')"),false);
assert.equal(run("quizBank.filter(q=>q.type==='match').length"),2);
assert.deepEqual(Array.from(run('placeQuizToken([-1,-1,-1],0,2)')),[2,-1,-1]);
assert.deepEqual(Array.from(run('placeQuizToken([0,1,-1],1,0)')),[1,0,-1]);
assert.deepEqual(Array.from(run('placeQuizToken([0,1,-1],2,0)')),[-1,1,0]);
assert.deepEqual(Array.from(run('placeQuizToken([0,1,-1],1,2)')),[0,2,-1]);
run("localStorage.removeItem(quizStateKey);recordQuizResult(extendedQuizBank.find(q=>q.type==='match'),true)");
assert.equal(run('quizState().attempts'),1);assert.equal(run('quizState().correct'),1);assert.equal(run('quizState().game.chain'),1);
assert.equal(run('gameDay(quizState()).puzzle.length'),1);
run("recordQuizResult(extendedQuizBank.find(q=>q.type==='match'),true)");assert.equal(run('gameDay(quizState()).puzzle.length'),1);
console.log('PASS: no short-answer questions; drag placement, swaps and moving to empty slots; automatic match grading; puzzle missions and correct-chain integration.');
