const vm=require('vm'),fs=require('fs'),assert=require('assert');
const src=fs.readFileSync('site/moba.js','utf8'),ctx=vm.createContext({});vm.runInContext(src+';this.Sim=MobaSimulation;this.path=mobaPath;this.walkable=mobaWalkable;this.direction=mobaDirection;',ctx);const Sim=ctx.Sim;let n=0;const check=(v,m)=>{assert(v,m);n++;};
function run(s,t){for(let i=0;i<Math.ceil(t/.025);i++)s.step(.025);}
function setup(champion='Zed'){const s=new Sim(champion);s.start();s.nextWave=999;s.heroes[1].aiAt=999;for(const u of s.units.filter(u=>u.type==='hound'))u.hp=0;s.heroes[0].x=480;s.heroes[0].y=360;s.heroes[1].x=700;s.heroes[1].y=360;return s;}
let s=setup();check(s.heroes[0].champion==='Zed'&&s.heroes[1].champion==='Naafiri','correct bodies');let hp=s.heroes[1].hp;check(s.cast(0,{x:1000,y:360}),'Q cast');run(s,.7);check(s.heroes[1].hp<hp,'Q real collision');check(!s.cast(0,{x:1000,y:360}),'Q cooldown');
s=setup();hp=s.heroes[1].hp;s.cast(0,{x:1000,y:510});run(s,1);check(s.heroes[1].hp>=hp,'misses do not damage');
s=setup();s.heroes[0].resource=1;check(!s.cast(0,s.heroes[1]),'resource guard');check(s.heroes[1].hp===hp,'guard does not damage');
s=setup();check(s.cast(1,{x:600,y:360}),'shadow placement');run(s,.4);check(s.shadows.length===1,'shadow exists');check(s.cast(1,{x:300,y:350}),'shadow swap');check(Math.abs(s.heroes[0].x-600)<1,'swap moves real body');check(s.heroes[0].cooldowns[1]>s.time+5,'swap does not reset cooldown');
s=setup();s.cast(1,{x:600,y:360});run(s,5.1);check(s.shadows.length===0,'shadow expiry');check(!s.cast(1,{x:650,y:360}),'expired shadow respects original cooldown');
s=setup();s.heroes[1].x=575;s.cast(1,{x:570,y:400});run(s,.3);hp=s.heroes[1].hp;s.cast(2,s.heroes[1]);check(s.heroes[1].hp<hp&&s.heroes[1].slowUntil>s.time,'E AoE and slow');
s=setup();check(!s.cast(3,{x:10,y:10}),'R must target hero');check(s.cast(3,s.heroes[1]),'R valid target');run(s,.5);check(s.marks.length===1,'death mark created');s.heroes[0].targetId=null;s.heroes[1].targetId=null;s.heroes[1].aiAt=999;const target=s.heroes[1];s.damage(target,100,s.heroes[0]);check(s.marks[0].stored>=100,'death mark stores damage');hp=target.hp;run(s,3.1);check(target.hp<hp-100,'mark explosion adds damage');
s=setup('Naafiri');hp=s.heroes[1].hp;check(s.cast(0,s.heroes[1]),'dagger cast');run(s,.5);check(s.bleeds.length===1,'dagger bleed');check(s.cast(0,s.heroes[1]),'dagger recast');run(s,.6);check(s.heroes[1].hp<hp-220,'second dagger amplifies');
s=setup('Naafiri');s.cast(0,{x:1000,y:550});run(s,3.2);check(!s.cast(0,s.heroes[1]),'unused recast preserves cooldown');
s=setup('Naafiri');check(s.cast(1,s.heroes[0]),'pack W');check(s.units.filter(u=>u.type==='hound'&&u.hp).length===3,'additional hounds');hp=s.heroes[0].hp;s.damage(s.heroes[0],100,s.heroes[1]);check(s.heroes[0].hp===hp,'W untargetability');run(s,.8);s.damage(s.heroes[0],100,s.heroes[1]);check(s.heroes[0].hp<hp,'untargetability expires');
s=setup('Naafiri');const oldX=s.heroes[0].x;check(s.cast(2,{x:650,y:360}),'hound dash');check(s.heroes[0].x>oldX+100,'dash moves body');
s=setup('Naafiri');check(s.cast(3,s.heroes[1]),'pursuit cast');run(s,.6);check(s.heroes[0].x>600&&s.heroes[1].hp<s.heroes[1].maxHP,'pursuit moves and damages');s.damage(s.heroes[1],9999,s.heroes[0]);check(s.heroes[0].pursuitRecast,'pursuit kill recast');
s=setup();const nexus=s.nexuses[1];hp=nexus.hp;s.damage(nexus,500,s.heroes[0]);check(nexus.hp===hp,'tower protects nexus');s.damage(s.towers[1],9999,s.heroes[0]);s.damage(nexus,9999,s.heroes[0]);check(s.winner===0&&!s.running,'nexus victory');
s=setup();s.damage(s.heroes[0],9999,s.heroes[1]);check(s.heroes[0].hp===0&&!s.cast(0,s.heroes[1]),'death locks skills');run(s,7.1);check(s.heroes[0].hp>0&&s.kills[1]===1,'respawn and kill count');
s=setup();s.paused=true;run(s,2);check(s.time===0,'pause freezes simulation');s.paused=false;run(s,.1);check(s.time>0,'resume');
s=setup();check(s.command({x:850,y:180}),'movement command');const path=ctx.path({x:280,y:205},{x:500,y:205});check(path.length>1&&path.every(p=>ctx.walkable(p)),'path routes around rocks');check(ctx.path({x:280,y:205},{x:385,y:205}).length===0,'blocked target rejected');
s=setup();const tower=s.towers[1];s.heroes[0].x=900;s.heroes[0].y=300;const min=s.unit('minion',0,905,300,300);s.units.push(min);run(s,.1);check(tower.targetId===min.id,'tower prioritizes wave');s.damage(s.heroes[1],1,s.heroes[0]);check(tower.targetId===s.heroes[0].id,'tower retaliates champion damage');
s=setup();const min2=s.unit('minion',1,650,350,50);s.units.push(min2);const gold=s.heroes[0].gold;s.damage(min2,100,s.heroes[0]);check(s.heroes[0].cs===1&&s.heroes[0].gold>=gold+25,'last hit gives gold');s.heroes[0].gold=400;check(!s.buy('sword'),'shop requires base');s.heroes[0].x=140;s.heroes[0].y=560;check(s.buy('sword')&&s.heroes[0].items.length===1,'base purchase');
s=setup();s.heroes[0].hp=500;s.recall();run(s,1);s.damage(s.heroes[0],1,s.heroes[1]);check(s.heroes[0].recallAt===0,'damage cancels recall');check(s.flash({x:600,y:390}),'flash');check(!s.flash({x:650,y:400}),'flash cooldown');
for(const hero of ['Zed','Naafiri']){s=new Sim(hero);s.start();s.auto=true;run(s,180);check(s.units.length<80,'bounded units');check(s.units.every(u=>Number.isFinite(u.hp)&&u.hp>=0&&Number.isFinite(u.x)&&Number.isFinite(u.y)),'long match finite state');check(s.heroes.every(h=>h.resource>=0&&h.resource<=h.maxResource),'resources bounded');check(s.wave>5,'minion waves advance');}
for(const hero of ['Zed','Naafiri']){s=new Sim(hero);s.start();s.auto=true;run(s,480);check(s.winner!==null&&s.nexuses.some(n=>n.hp===0),'complete AI match reaches nexus victory');}
for(let i=0;i<8;i++)check(ctx.direction(i*Math.PI/4)===i,'eight directions map exact angle');check(ctx.direction(-Math.PI/4)===7&&ctx.direction(2*Math.PI)===0,'direction wrap');
// Practice isolation and actual dummy hit statistics.
s=new Sim('Zed');s.reset('Zed',true);s.start();const dummy=s.heroes[1],origin={x:dummy.x,y:dummy.y};run(s,20);check(dummy.x===origin.x&&dummy.y===origin.y&&s.heroes[0].hp===s.heroes[0].maxHP,'dummy never moves or attacks');check(s.wave===0&&!s.units.some(u=>u.type==='minion'),'practice has no waves');check(s.cast(0,dummy),'dummy aimed Q');run(s,1);check(s.training.damage>0&&s.training.hits>0,'real projectile increments statistics');const before=s.training.damage;s.heroes[0].cooldowns.fill(0);s.cast(0,{x:900,y:560});run(s,1);check(s.training.damage===before,'miss adds no dummy damage');s.damage(dummy,999999,s.heroes[0]);check(dummy.hp===dummy.maxHP&&s.kills[0]===0&&s.heroes[0].xp===0,'dummy restores without kill or xp reward');check(s.refreshPractice()&&s.training.damage===0&&s.projectiles.length===0&&s.marks.length===0&&s.running,'practice reset clears damage and transient effects');s.unlimited=true;s.heroes[0].resource=0;s.heroes[0].cooldowns.fill(999);run(s,.1);check(s.heroes[0].resource===s.heroes[0].maxResource&&s.cast(0,dummy),'unlimited resources and cooldowns work');s.reset('Naafiri',false);s.start();s.heroes[0].resource=0;run(s,.1);check(s.heroes[0].resource<10,'practice unlimited cannot leak into real match');
s=new Sim('Zed');s.reset('Zed',true);s.start();s.cast(3,s.heroes[1]);run(s,.6);s.damage(s.heroes[1],100,s.heroes[0]);check(s.marks[0].stored>=100,'dummy supports death mark storage');run(s,3);check(s.training.damage>=235,'dummy includes mark explosion');s.paused=true;const frozen=s.training.damage;run(s,5);check(s.training.damage===frozen,'practice pauses damage and timers');
// Canvas input handler: real keyboard events routed to quick cast or preview.
const listeners={};ctx.Image=class{};ctx.ResizeObserver=class{observe(){}};ctx.IntersectionObserver=class{observe(){}};ctx.window={devicePixelRatio:1};ctx.requestAnimationFrame=()=>{};ctx.document={addEventListener(){},querySelector(){return null;},querySelectorAll(){return []}};vm.runInContext('this.Canvas=MobaCanvas;',ctx);const renderer=new ctx.Canvas({getContext:()=>({}),addEventListener:(k,fn)=>listeners[k]=fn,focus(){},getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720})});renderer.updateUI=()=>{};renderer.loaded=true;renderer.sim.reset('Zed',true);renderer.sim.start();renderer.mouse={x:720,y:300};let prevented=0;const key=(key,extra={})=>listeners.keydown({key,preventDefault(){prevented++;},...extra});key('q');check(renderer.sim.projectiles.length===1&&renderer.armed===null,'quick Q fires immediately at hovered dummy body');key('q');check(renderer.sim.projectiles.length===1,'quick cooldown prevents repeated cast');key('w',{shiftKey:true});check(renderer.armed===1&&renderer.sim.shadows.length===0,'Shift previews without casting');renderer.armed=null;renderer.quickCast=false;key('e');check(renderer.armed===2,'normal cast arms for confirmation');renderer.quickCast=true;renderer.armed=null;key('w',{repeat:true});check(renderer.sim.shadows.length===0,'repeated key ignored');renderer.sim.paused=true;key('w');check(renderer.sim.shadows.length===0,'paused quick cast blocked');check(prevented>=4,'skill keys prevent page shortcuts');
// Painted props must select the correct team half and stay within image bounds.
const draws=[];renderer.props={naturalWidth:1536,naturalHeight:1024};renderer.ctx={save(){},restore(){},drawImage(...args){draws.push(args);}};for(let col=0;col<4;col++)for(let team=0;team<2;team++)renderer.worldObject(col,team,500,400,100,150);check(draws.length===8,'all object variants render');check(draws.every(a=>a[1]>=0&&a[2]>=0&&a[1]+a[3]<=1536&&a[2]+a[4]<=1024),'object source rectangles stay inside atlas');check(draws[3][1]===385&&draws[3][2]===512&&draws[3][3]===470,'red nexus uses inspected full object bounds');check(draws[4][1]===860&&draws[6][1]===1235,'melee and caster use separate inspected cells');renderer.props={naturalWidth:768,naturalHeight:512};renderer.worldObject(1,1,500,400,100,150);check(draws.at(-1)[1]===192.5&&draws.at(-1)[2]===256,'atlas crop scales with actual source resolution');
check(!/localStorage|competitionCall|saveQuizState|\.rpc\(/.test(src),'no persistence or competition writes');
console.log(n+' checks passed: real skill hits/misses, resources, cooldowns, shadows, marks, hounds, dashes, tower aggro, nexus shields, death/respawn, pathfinding, waves, last hits, shop, pause, long AI matches and score separation.');
