
    let records=[], active='全部', selected=null;
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const cls=s=>s==='已取消'?'cancel':s==='有效'?'valid':s==='移交其他主題'?'transfer':'pending';
    async function init(){const response=await fetch('./data.json');if(!response.ok)throw new Error('資料讀取失敗');const d=await response.json();records=d.records;document.querySelector('#updated').textContent='資料基準 · '+d.updated_at.slice(0,10);drawFilters();render();const id=decodeURIComponent(location.hash.slice(1));if(records.some(r=>r.id===id))show(id);}
    function drawFilters(){const fs=['全部','有效','已取消','移交其他主題','待定','待確認／衝突'];document.querySelector('#filters').innerHTML=fs.map(x=>`<button class="chip ${x===active?'active':''}" data-f="${x}">${x}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{active=b.dataset.f;selected=null;drawFilters();render()})}
    function filtered(){const q=document.querySelector('#q').value.trim().toLowerCase();return records.filter(r=>{const blob=JSON.stringify(r).toLowerCase();const f=active==='全部'||r.rule_status===active||(active==='待確認／衝突'&&['待確認','衝突','待後續定案'].includes(r.evidence_status));return f&&(!q||blob.includes(q))})}
    function render(){const rs=filtered();document.querySelector('#summary').innerHTML=[['知識規則',records.length],['正式來源規則',records.filter(r=>r.source_type.includes('SSR')).length],['待確認／衝突',records.filter(r=>['待確認','衝突'].includes(r.evidence_status)).length],['L6已追溯',records.filter(r=>r.l6_ids?.length).length]].map(([a,b])=>`<div class="metric"><strong>${b}</strong><span>${a}</span></div>`).join('');document.querySelector('#list').innerHTML=rs.length?rs.map(r=>`<button class="item ${r.id===selected?'active':''}" data-id="${esc(r.id)}"><div class="item-id">${esc(r.id)}</div><div class="item-title">${esc(r.title)}</div><div class="tags"><span class="tag ${cls(r.rule_status)}">${esc(r.rule_status)}</span><span class="tag">${esc(r.evidence_status)}</span><span class="tag">${esc(r.topic)}</span></div></button>`).join(''):'<div class="empty">找不到符合條件的知識</div>';document.querySelectorAll('.item').forEach(b=>b.onclick=()=>show(b.dataset.id));document.querySelector('#result-count').textContent=rs.length+' 筆結果';if(!selected&&rs[0])show(rs[0].id);if(!rs.length)document.querySelector('#detail').innerHTML='<div class="empty">沒有符合條件的知識，請調整搜尋或篩選。</div>'}
    function show(id){selected=id;const r=records.find(x=>x.id===id);if(!r)return;history.replaceState(null,'','#'+encodeURIComponent(id));document.querySelectorAll('.item').forEach(x=>x.classList.toggle('active',x.dataset.id===id));document.querySelector('#detail').innerHTML=`<div class="item-id">${esc(r.id)} · ${esc(r.topic)}</div><h2>${esc(r.title)}</h2><div class="tags"><span class="tag ${cls(r.rule_status)}">規則：${esc(r.rule_status)}</span><span class="tag">證據：${esc(r.evidence_status)}</span><span class="tag">${esc(r.source_type)}</span></div><p class="lead">${esc(r.plain_language)}</p><section class="section"><h3>條件與結果</h3><div class="kv"><div class="k">業務目的</div><div>${esc(r.goal)}</div><div class="k">觸發事件</div><div>${esc(r.trigger)}</div><div class="k">處理結果</div><div>${esc(r.result)}</div><div class="k">代碼</div><div>${r.codes?.map(esc).join('、')||'—'}</div></div></section><section class="section"><h3>適用條件</h3><ul class="conditions">${r.conditions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="section"><h3>來源與追溯</h3>${r.sources.map(s=>`<div class="source"><b>${esc(s.document)}</b>${esc(s.location)}</div>`).join('')}<div class="source"><b>Requirement</b>${r.requirement_ids?.map(esc).join('<br>')||'尚未取得'}</div><div class="source"><b>L6</b>${r.l6_ids?.map(esc).join('<br>')||'尚未取得／待確認承接覆蓋'}</div></section>${r.notes?.length?`<section class="section"><h3>易錯觀念與待確認</h3><ul>${r.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}`}
    document.querySelector('#q').addEventListener('input',()=>{selected=null;render()});init().catch(()=>document.querySelector('#detail').innerHTML='<div class="empty">知識資料載入失敗</div>');
  
window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(records.some(r=>r.id===id))show(id)});
